# Translations template for PROJECT.
# Copyright (C) 2025 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2025-04-30 11:23-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.16.0\n"

#: minarca_client/main.py:46
msgid "Operation aborted by the user."
msgstr ""

#: minarca_client/main.py:55
msgid "yes"
msgstr ""

#: minarca_client/main.py:55
msgid "y"
msgstr ""

#: minarca_client/main.py:66
#, python-format
msgid "new version %s available"
msgstr ""

#: minarca_client/main.py:68
msgid "fail to check for latest version"
msgstr ""

#: minarca_client/main.py:81
msgid "Backup Instances:"
msgstr ""

#: minarca_client/main.py:83 minarca_client/main.py:356
#: minarca_client/ui/backup_card.py:21
msgid "No name"
msgstr ""

#: minarca_client/main.py:85
msgid "Are you sure you want to forget the above backup settings? (Yes/No): "
msgstr ""

#: minarca_client/main.py:108
msgid ""
"Do you want to backup to a local device (external disk or network share)?"
" (Yes/No): "
msgstr ""

#: minarca_client/main.py:114
msgid "Enter the local destination path: "
msgstr ""

#: minarca_client/main.py:134
msgid "Remote URL (e.g.: https://backup.examples.com): "
msgstr ""

#: minarca_client/main.py:136
msgid "Username: "
msgstr ""

#: minarca_client/main.py:138
msgid "Password or access token: "
msgstr ""

#: minarca_client/main.py:154 minarca_client/main.py:159
msgid "Linked successfully"
msgstr ""

#: minarca_client/main.py:157
msgid "Do you want to replace the existing repository? (Yes/No): "
msgstr ""

#: minarca_client/main.py:173
msgid ""
"To update include or exclude patterns, you must configure at least one "
"backup instance."
msgstr ""

#: minarca_client/main.py:241
msgid "From which backup source do you want to restore data from?"
msgstr ""

#: minarca_client/main.py:253
msgid "Enter backup instance ID: "
msgstr ""

#: minarca_client/main.py:257
#, python-format
msgid "Invalid instance ID: %s"
msgstr ""

#: minarca_client/main.py:261
msgid "Your instance value doesn't match any backup instances"
msgstr ""

#: minarca_client/main.py:263
msgid "Your instance value matches too many backup instances"
msgstr ""

#: minarca_client/main.py:276
#, python-format
msgid "Do you want to restore %s? (Yes/No): "
msgstr ""

#: minarca_client/main.py:290
msgid ""
"Are you sure you want to proceed with the restore operation? Please note "
"that this will override your current data. (Yes/No): "
msgstr ""

#: minarca_client/main.py:356
#, python-format
msgid "Backup Instance: %s"
msgstr ""

#: minarca_client/main.py:360
#, python-format
msgid "Identifier:             %s"
msgstr ""

#: minarca_client/main.py:362
#, python-format
msgid "Remote server:          %s"
msgstr ""

#: minarca_client/main.py:364
#, python-format
msgid "Local device:           %s"
msgstr ""

#: minarca_client/main.py:365
#, python-format
msgid "Connectivity status:    %s"
msgstr ""

#: minarca_client/main.py:365
msgid "Connected"
msgstr ""

#: minarca_client/main.py:365
msgid "Not connected"
msgstr ""

#: minarca_client/main.py:368
#, python-format
msgid "Last successful backup: %s"
msgstr ""

#: minarca_client/main.py:368 minarca_client/main.py:370
#: minarca_client/main.py:371 minarca_client/ui/backup_settings.py:257
msgid "Never"
msgstr ""

#: minarca_client/main.py:370
#, python-format
msgid "Last backup date:       %s"
msgstr ""

#: minarca_client/main.py:371
#, python-format
msgid "Last backup status:     %s"
msgstr ""

#: minarca_client/main.py:373
#, python-format
msgid "Details:                %s"
msgstr ""

#: minarca_client/main.py:375
#, python-format
msgid "Paused until:           %s"
msgstr ""

#: minarca_client/main.py:393
msgid "Minarca"
msgstr ""

#: minarca_client/main.py:394
msgid "Application failed to start"
msgstr ""

#: minarca_client/main.py:395
msgid ""
"If the problem persists, check the logs with your administrator or try "
"reinstalling the application."
msgstr ""

#: minarca_client/main.py:417
msgid ""
"Minarca manages your computer's backup by linking your computer with a "
"centralized server and running backups on a given schedule."
msgstr ""

#: minarca_client/main.py:436
msgid "start a backup in background mode"
msgstr ""

#: minarca_client/main.py:437 minarca_client/main.py:449
msgid "force execution of a backup even if it's not time to run"
msgstr ""

#: minarca_client/main.py:441 minarca_client/main.py:453
msgid "Limit backup to the given instance(s)."
msgstr ""

#: minarca_client/main.py:448
msgid "start a backup in foreground mode"
msgstr ""

#: minarca_client/main.py:460
msgid "exclude files from being backed up"
msgstr ""

#: minarca_client/main.py:464
msgid "Add exclude file pattern to the given instance(s)."
msgstr ""

#: minarca_client/main.py:468 minarca_client/main.py:481
msgid "file pattern to be excluded. May contain `*` or `?` wildcard"
msgstr ""

#: minarca_client/main.py:473
msgid "include files to be backed up"
msgstr ""

#: minarca_client/main.py:477
msgid "Add include file pattern to the given instance(s)."
msgstr ""

#: minarca_client/main.py:487
msgid "configure this agent to backup to a new destination (remote or local)"
msgstr ""

#: minarca_client/main.py:489
msgid "URL to the remote server. e.g.: http://example.com:8080/"
msgstr ""

#: minarca_client/main.py:490
msgid "username to be used for authentication with the remote server"
msgstr ""

#: minarca_client/main.py:494
msgid ""
"password or access token to use for authentication. You will be prompted "
"if not provided"
msgstr ""

#: minarca_client/main.py:496
msgid "repository name to be used"
msgstr ""

#: minarca_client/main.py:500
msgid ""
"replace existing repository on backup destination if it exists without "
"confirmation"
msgstr ""

#: minarca_client/main.py:502
msgid "path to local destination"
msgstr ""

#: minarca_client/main.py:506
msgid "list the include/exclude patterns"
msgstr ""

#: minarca_client/main.py:510
msgid "Show include and exclude patterns only for the given instance(s)."
msgstr ""

#: minarca_client/main.py:517
msgid "restore data from backup"
msgstr ""

#: minarca_client/main.py:521
msgid "Force the use of a given instance for restore."
msgstr ""

#: minarca_client/main.py:527
msgid ""
"Date and time to be restored. Could be 'now' to restore the latest "
"backup. Could be an epoch value like '1682367069'. Could be an ISO date "
"format like '2023-02-24T04:11:09-04:00'. Could be an interval like '3D' "
"for 3 days ago."
msgstr ""

#: minarca_client/main.py:533
msgid ""
"Define an alternate location to restore files or folders instead of "
"restoring them in place."
msgstr ""

#: minarca_client/main.py:538
msgid "Force execution of restore operation without confirmation from the user."
msgstr ""

#: minarca_client/main.py:540
msgid "files and folders to be restored"
msgstr ""

#: minarca_client/main.py:544
msgid "stop the backup"
msgstr ""

#: minarca_client/main.py:548
msgid "Stop only the given instance(s)."
msgstr ""

#: minarca_client/main.py:552
msgid "doesn't fail if the backup is not running."
msgstr ""

#: minarca_client/main.py:557
msgid "create the required scheduled task in Windows Task Scheduler"
msgstr ""

#: minarca_client/main.py:559
msgid "create the required scheduled task in launchd"
msgstr ""

#: minarca_client/main.py:561
msgid "create the required scheduled task in crontab"
msgstr ""

#: minarca_client/main.py:568
msgid "schedule backup to run hourly"
msgstr ""

#: minarca_client/main.py:575
msgid "schedule backup to run daily"
msgstr ""

#: minarca_client/main.py:582
msgid "schedule backup to run weekly"
msgstr ""

#: minarca_client/main.py:587
msgid "Configure only the given instance(s)."
msgstr ""

#: minarca_client/main.py:592
msgid "username required to run task when the user is logged out"
msgstr ""

#: minarca_client/main.py:593
msgid "password required to run task when the user is logged out"
msgstr ""

#: minarca_client/main.py:597
msgid "return the current Minarca status"
msgstr ""

#: minarca_client/main.py:601
msgid "Show status for the given instance(s)."
msgstr ""

#: minarca_client/main.py:608
msgid "forget backup settings"
msgstr ""

#: minarca_client/main.py:612
msgid "Forget settings of the given backup instance(s)."
msgstr ""

#: minarca_client/main.py:617
msgid "Force forget operation without confirmation from the user."
msgstr ""

#: minarca_client/main.py:624
msgid ""
"temporarily delay the execution of the backup for the given number of "
"hours. Default is 24 hours."
msgstr ""

#: minarca_client/main.py:629
msgid "Pause only the given instance(s)."
msgstr ""

#: minarca_client/main.py:633
msgid "number of hours"
msgstr ""

#: minarca_client/main.py:638
msgid "clear previously set delay"
msgstr ""

#: minarca_client/main.py:647
msgid "verify backup integrity"
msgstr ""

#: minarca_client/main.py:651
msgid "Verify backup integrity of the given backup instance(s)."
msgstr ""

#: minarca_client/main.py:658
msgid "open graphical user interface (default when calling minarcaw)"
msgstr ""

#: minarca_client/main.py:664
msgid "For internal use"
msgstr ""

#: minarca_client/core/exceptions.py:60
#, python-format
msgid "No backup instances match: %s"
msgstr ""

#: minarca_client/core/exceptions.py:77
#, python-format
msgid "Destination `%s` already exists."
msgstr ""

#: minarca_client/core/exceptions.py:90
msgid "cannot stop process when it's not running."
msgstr ""

#: minarca_client/core/exceptions.py:150
#, python-format
msgid "process terminated with an exception. Check logs for more details: %s"
msgstr ""

#: minarca_client/core/exceptions.py:165
#, python-format
msgid "process returned a non-zero exit status (%s). Check logs for more details"
msgstr ""

#: minarca_client/core/exceptions.py:183
msgid "cannot start process when it's already running."
msgstr ""

#: minarca_client/core/exceptions.py:195
msgid "backup not yet scheduled to run. You may force execution using `--force`"
msgstr ""

#: minarca_client/core/exceptions.py:211
msgid ""
"Unable to connect to the remote server. The problem may be with the "
"remote server. If the problem persists, contact your system administrator"
" to check the SSH server configuration and a possible firewall blocking "
"the connection."
msgstr ""

#: minarca_client/core/exceptions.py:234
msgid ""
"The connection to the remote server failed because our identity was "
"refused. The problem may lie with the remote server. If the problem "
"persists, contact your system administrator to check your SSH identity."
msgstr ""

#: minarca_client/core/exceptions.py:252
msgid ""
"The connection to the remote server cannot be established securely "
"because the server's identity has changed. If the problem persists, "
"contact your system administrator to verify the server's identity."
msgstr ""

#: minarca_client/core/exceptions.py:268
msgid ""
"Backup failed due to disk quota exceeded. Please free up disk space to "
"ensure successful backup."
msgstr ""

#: minarca_client/core/exceptions.py:280
msgid ""
"Backup failed due to disk being full. Please clear space on the disk to "
"proceed with the backup."
msgstr ""

#: minarca_client/core/exceptions.py:293
msgid ""
"The connection to the remote server has failed due to an unresolvable "
"host name. Please check your network connection and ensure that the host "
"name is still valid. If the problem persists, contact your system "
"administrator to check the host name."
msgstr ""

#: minarca_client/core/exceptions.py:310
msgid ""
"The connection to the remote server has failed due to an unsupported "
"version of the Minarca agent on the remote server. Consider updating your"
" agent or server."
msgstr ""

#: minarca_client/core/exceptions.py:324
msgid "The path you are trying to restore from backup does not exist."
msgstr ""

#: minarca_client/core/exceptions.py:337
msgid "Another backup session is currently in progress on the remote server."
msgstr ""

#: minarca_client/core/exceptions.py:350
msgid ""
"An internal error was raised by an unknown operation sent to the "
"background process."
msgstr ""

#: minarca_client/core/exceptions.py:363
msgid ""
"Backup Destination Not Found. Please ensure that your external disk or "
"network share is properly connected and accessible."
msgstr ""

#: minarca_client/core/exceptions.py:370
msgid ""
"Backup unsuccessful due to a copy operation encountering an issue, "
"potentially because the device is disconnected. Ensure your device is "
"properly connected."
msgstr ""

#: minarca_client/core/exceptions.py:385
msgid "Repository cannot be found on remote server"
msgstr ""

#: minarca_client/core/exceptions.py:391
#, python-format
msgid "Repository `%s` cannot be found on remote server"
msgstr ""

#: minarca_client/core/exceptions.py:415
msgid ""
"The connection was terminated unexpectedly, which may indicate an issue "
"with the remote server. If the problem persists, contact your system "
"administrator to review the server logs and diagnose the cause."
msgstr ""

#: minarca_client/core/exceptions.py:432
#, python-format
msgid ""
"your file specification [%s] doesn't match any of the base directories of"
" your system"
msgstr ""

#: minarca_client/core/exceptions.py:453
msgid "No files included in backup. Check configuration."
msgstr ""

#: minarca_client/core/exceptions.py:467
msgid "not configured, use `minarca configure` to configure remote host"
msgstr ""

#: minarca_client/core/exceptions.py:480
msgid "Cannot establish connection to remote server."
msgstr ""

#: minarca_client/core/exceptions.py:481
#, python-format
msgid ""
"Your computer cannot establish a connection to the remote server. Make "
"sure your Internet connection is working and that the following URL is "
"accessible with a Web browser: %s"
msgstr ""

#: minarca_client/core/exceptions.py:497
#, python-format
msgid "Invalid remote server URL: %s"
msgstr ""

#: minarca_client/core/exceptions.py:498
msgid ""
"The remote server URL you entered for the connection is not valid. Check "
"that you have entered the correct value. The URL must begin with "
"`http://` or `https://` followed by a domain name."
msgstr ""

#: minarca_client/core/exceptions.py:515
msgid "Invalid username or password"
msgstr ""

#: minarca_client/core/exceptions.py:516
msgid ""
"The username or password you entered to connect to the remote server is "
"not valid. If you have enabled multi-factor authentication, you need to "
"use an access token."
msgstr ""

#: minarca_client/core/exceptions.py:533
msgid "The remote server returned an error. You may try again later."
msgstr ""

#: minarca_client/core/exceptions.py:545
msgid "Backup Destination Occupied"
msgstr ""

#: minarca_client/core/exceptions.py:546
msgid ""
"Unable to proceed with the selected destination as it contains existing "
"data. If you intend to use this location, kindly empty the directory of "
"any files and folders."
msgstr ""

#: minarca_client/core/exceptions.py:557
msgid "Destination Not Suitable"
msgstr ""

#: minarca_client/core/exceptions.py:558
msgid ""
"Unable to proceed with the selected destination as it cannot be "
"initialized. Make sure the external device is connected and operational."
msgstr ""

#: minarca_client/core/exceptions.py:569
msgid ""
"Repository name must contain only letters, numbers, dashes (-), and dots "
"(.)"
msgstr ""

#: minarca_client/core/exceptions.py:583
msgid ""
"These settings conflict with an existing backup and therefore cannot be "
"created."
msgstr ""

#: minarca_client/core/exceptions.py:584
msgid ""
"It is not possible to create two backups with the same destination "
"settings. These will conflict during backup. Be sure to define a "
"different destination for this backup."
msgstr ""

#: minarca_client/core/exceptions.py:605
msgid ""
"The remote server could not create the necessary security context, which "
"may indicate an issue with the server. If the problem persists, please "
"contact your system administrator to review the server logs and diagnose "
"the cause."
msgstr ""

#: minarca_client/core/latest.py:31
msgid "https://minarca.org/download/"
msgstr ""

#: minarca_client/core/pattern.py:87
msgid "User's Documents"
msgstr ""

#: minarca_client/core/pattern.py:89
msgid "Minarca Config"
msgstr ""

#: minarca_client/core/pattern.py:96 minarca_client/core/pattern.py:155
#: minarca_client/core/pattern.py:176
msgid "Firefox Bookmark"
msgstr ""

#: minarca_client/core/pattern.py:103 minarca_client/core/pattern.py:162
#: minarca_client/core/pattern.py:177
msgid "Chrome Bookmark"
msgstr ""

#: minarca_client/core/pattern.py:110
msgid "Outlook Offline Data"
msgstr ""

#: minarca_client/core/pattern.py:117
msgid "Outlook Address Books"
msgstr ""

#: minarca_client/core/pattern.py:122
msgid "Thumbnails cache"
msgstr ""

#: minarca_client/core/pattern.py:123
msgid "Arrangement of a Windows folder"
msgstr ""

#: minarca_client/core/pattern.py:124
msgid "Swap System File"
msgstr ""

#: minarca_client/core/pattern.py:125
msgid "Page System File"
msgstr ""

#: minarca_client/core/pattern.py:126
msgid "Hibernation System File"
msgstr ""

#: minarca_client/core/pattern.py:127
msgid "System Volume Information"
msgstr ""

#: minarca_client/core/pattern.py:128
msgid "System Recovery"
msgstr ""

#: minarca_client/core/pattern.py:129
msgid "Recycle bin"
msgstr ""

#: minarca_client/core/pattern.py:130 minarca_client/core/pattern.py:183
msgid "Temporary Folder"
msgstr ""

#: minarca_client/core/pattern.py:131
msgid "AutoCAD backup files"
msgstr ""

#: minarca_client/core/pattern.py:132
msgid "Office temporary files"
msgstr ""

#: minarca_client/core/pattern.py:133
msgid "Outlook IMAP temporary files"
msgstr ""

#: minarca_client/core/pattern.py:134
msgid "Outlook POP temporary files"
msgstr ""

#: minarca_client/core/pattern.py:135
msgid "Dynacom Backup file"
msgstr ""

#: minarca_client/core/pattern.py:136
msgid "Google Drive temporary upload files"
msgstr ""

#: minarca_client/core/pattern.py:137
msgid "Google Drive temporary download files"
msgstr ""

#: minarca_client/core/pattern.py:142 minarca_client/core/pattern.py:171
msgid "OneDrive GUID File"
msgstr ""

#: minarca_client/core/pattern.py:145
msgid "Google Drive Shortcut Metadata"
msgstr ""

#: minarca_client/core/pattern.py:146
msgid "Google Drive Revision History"
msgstr ""

#: minarca_client/core/pattern.py:147
msgid "Google Drive Encrypted"
msgstr ""

#: minarca_client/core/pattern.py:167
msgid "Desktop Services Store"
msgstr ""

#: minarca_client/core/pattern.py:180
msgid "dev filesystem"
msgstr ""

#: minarca_client/core/pattern.py:181
msgid "proc filesystem"
msgstr ""

#: minarca_client/core/pattern.py:182
msgid "sys filesystem"
msgstr ""

#: minarca_client/core/pattern.py:184
msgid "Volatile program files"
msgstr ""

#: minarca_client/core/pattern.py:185
msgid "Mounted filesystems"
msgstr ""

#: minarca_client/core/pattern.py:186
msgid "External media"
msgstr ""

#: minarca_client/core/pattern.py:187
msgid "Ext4 Lost and Found"
msgstr ""

#: minarca_client/core/pattern.py:188
msgid "Hidden temporary files"
msgstr ""

#: minarca_client/core/pattern.py:189
msgid "Vim temporary files"
msgstr ""

#: minarca_client/core/scheduler.py:23
msgid "Minarca Backup"
msgstr ""

#: minarca_client/core/scheduler.py:76
msgid ""
"Keeps your Minarca Backup Software running. If this task is disabled or "
"stopped, your Minarca backup will stop working. This task gets created "
"when linking Minarca with a central backup server. When installing "
"Minarca on a Windows Server, it's preferable to change the settings of "
"this task and select 'Run whether user is logged on or not' to make sure "
"the backup is running even when nobody is using the server."
msgstr ""

#: minarca_client/core/scheduler.py:106
msgid ""
"A problem prevents the scheduling of backup jobs. Try running the "
"application with Administrator rights."
msgstr ""

#: minarca_client/core/scheduler.py:113
msgid ""
"The user account is unknown or the password is incorrect. Be sure to "
"enter your Windows credentials."
msgstr ""

#: minarca_client/core/status.py:152
msgid "Your backup is outdated"
msgstr ""

#: minarca_client/core/status.py:153
#, python-format
msgid ""
"Your backup %s is outdated by over %s days. Please plug in your local "
"device and run the backup."
msgstr ""

#: minarca_client/core/notification/_notification_win.py:127
msgid "Show details"
msgstr ""

#: minarca_client/dialogs/_dialogs_cocoa.py:57
msgid "Yes"
msgstr ""

#: minarca_client/dialogs/_dialogs_cocoa.py:57
msgid "No"
msgstr ""

#: minarca_client/ui/about_menu.py:20
#: minarca_client/ui/backup_connection_local.py:30
msgid "Browse"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Settings"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Get Help"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Help"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Website"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Minarca Agent"
msgstr ""

#: minarca_client/ui/about_menu.py:20
#, python-format
msgid "Version %s"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Update now"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Copyright © 2025 IKUS Software"
msgstr ""

#: minarca_client/ui/about_menu.py:128 minarca_client/ui/about_menu.py:130
#: minarca_client/ui/backup_connection_local.py:262
#, python-format
msgid "%s on %s"
msgstr ""

#: minarca_client/ui/about_menu.py:228
msgid "Checking for updates..."
msgstr ""

#: minarca_client/ui/about_menu.py:230
msgid "Unable to verify update availability at this time."
msgstr ""

#: minarca_client/ui/about_menu.py:232
#, python-format
msgid "New version %s available"
msgstr ""

#: minarca_client/ui/about_menu.py:234
msgid "Current version is up-to-date"
msgstr ""

#: minarca_client/ui/backup_advance.py:19
msgid "Configure your advanced backup settings to fine-tune your preferences."
msgstr ""

#: minarca_client/ui/backup_advance.py:19
msgid "Script hooks"
msgstr ""

#: minarca_client/ui/backup_advance.py:19
msgid ""
"Set up custom scripts to run before or after backups by defining the "
"command line to be executed."
msgstr ""

#: minarca_client/ui/backup_advance.py:19
msgid "Pre-backup command"
msgstr ""

#: minarca_client/ui/backup_advance.py:19
msgid "Post-backup command"
msgstr ""

#: minarca_client/ui/backup_advance.py:19
msgid "Continue the backup if one of the command fails"
msgstr ""

#: minarca_client/ui/backup_advance.py:19
#: minarca_client/ui/backup_connection_local.py:30
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_patterns.py:23
#: minarca_client/ui/backup_settings.py:26
msgid "Cancel"
msgstr ""

#: minarca_client/ui/backup_advance.py:19
#: minarca_client/ui/backup_connection_local.py:30
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_patterns.py:23
#: minarca_client/ui/backup_settings.py:26
msgid "Save"
msgstr ""

#: minarca_client/ui/backup_advance.py:127
#: minarca_client/ui/backup_settings.py:350
msgid "Please wait. Saving settings..."
msgstr ""

#: minarca_client/ui/backup_advance.py:144
msgid "Cannot save advance settings"
msgstr ""

#: minarca_client/ui/backup_advance.py:145
msgid ""
"An unknown problem encountered while trying to save the advance backup "
"settings. If the problem persist contact your administrator."
msgstr ""

#: minarca_client/ui/backup_card.py:21 minarca_client/ui/backup_create.py:11
#: minarca_client/ui/side_pannel.py:102
msgid "Online backup"
msgstr ""

#: minarca_client/ui/backup_card.py:21 minarca_client/ui/backup_create.py:11
#: minarca_client/ui/side_pannel.py:109
msgid "Local backup"
msgstr ""

#: minarca_client/ui/backup_card.py:21
msgid "Paused"
msgstr ""

#: minarca_client/ui/backup_card.py:21
msgid "Active"
msgstr ""

#: minarca_client/ui/backup_card.py:21 minarca_client/ui/backup_settings.py:26
msgid "Backup configuration"
msgstr ""

#: minarca_client/ui/backup_card.py:21
#: minarca_client/ui/backup_restore_files.py:28
msgid "File selection"
msgstr ""

#: minarca_client/ui/backup_card.py:21
msgid "Advance settings"
msgstr ""

#: minarca_client/ui/backup_card.py:21
msgid "Restore backup"
msgstr ""

#: minarca_client/ui/backup_card.py:293
msgid "Calculating disk usage"
msgstr ""

#: minarca_client/ui/backup_card.py:295
msgid "Cannot determine disk usage"
msgstr ""

#: minarca_client/ui/backup_card.py:296
#, python-format
msgid "Used space %s"
msgstr ""

#: minarca_client/ui/backup_card.py:304
#, python-format
msgid "Total space %s"
msgstr ""

#: minarca_client/ui/backup_card.py:309
msgid "Stopping..."
msgstr ""

#: minarca_client/ui/backup_card.py:309
msgid "Starting..."
msgstr ""

#: minarca_client/ui/backup_card.py:314
msgid "Stop Restore"
msgstr ""

#: minarca_client/ui/backup_card.py:315
msgid "Stop Backup"
msgstr ""

#: minarca_client/ui/backup_card.py:317
msgid "Start Backup now"
msgstr ""

#: minarca_client/ui/backup_card.py:325 minarca_client/ui/backup_logs.py:286
msgid "No backup yet"
msgstr ""

#: minarca_client/ui/backup_card.py:329
msgid "Backup in progress..."
msgstr ""

#: minarca_client/ui/backup_card.py:330 minarca_client/ui/backup_logs.py:290
#, python-format
msgid "Last backup: %s"
msgstr ""

#: minarca_client/ui/backup_card.py:333
msgid "Restore in progress..."
msgstr ""

#: minarca_client/ui/backup_card.py:334 minarca_client/ui/backup_logs.py:292
#, python-format
msgid "Last restore: %s"
msgstr ""

#: minarca_client/ui/backup_card.py:341
#: minarca_client/ui/backup_connection_remote.py:21
msgid "Server connection"
msgstr ""

#: minarca_client/ui/backup_card.py:341
msgid "Local connection"
msgstr ""

#: minarca_client/ui/backup_card.py:385
msgid "Pause Backup Job Confirmation"
msgstr ""

#: minarca_client/ui/backup_card.py:386
msgid "Are you sure you want to pause the backup job?"
msgstr ""

#: minarca_client/ui/backup_card.py:387
msgid ""
"Pausing the backup job will temporarily suspend the ongoing backup "
"process for the next 24 hours. This action may affect the availability of"
" recent data restore points and introduce delays in the backup schedule. "
"Please confirm your intention before proceeding."
msgstr ""

#: minarca_client/ui/backup_card.py:406
msgid "Start Backup"
msgstr ""

#: minarca_client/ui/backup_card.py:407
msgid "A problem occurred when trying to start the backup process."
msgstr ""

#: minarca_client/ui/backup_card.py:408
msgid ""
"This usually indicate a problem with the installation. Try re-installing "
"Minarca Backup."
msgstr ""

#: minarca_client/ui/backup_card.py:422 minarca_client/ui/backup_logs.py:346
msgid "Stop process"
msgstr ""

#: minarca_client/ui/backup_card.py:423 minarca_client/ui/backup_logs.py:347
msgid "A problem occurred when trying to stop the process."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:30
msgid "Select a location to be used for backing up your data."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:30
msgid "Target location"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:30
msgid "Edit target location"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:30
#: minarca_client/ui/backup_connection_remote.py:21
msgid "Backup name"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:30
msgid "Refresh"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:30
msgid ""
"No external drive has been detected for data backup. Plug in your "
"external drive and click on the refresh button to update this list. If "
"your device is not on the list, check its connectivity and make sure it's"
" switched on."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:30
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_create.py:11 minarca_client/ui/backup_logs.py:26
#: minarca_client/ui/backup_restore_date.py:25
#: minarca_client/ui/backup_restore_files.py:28
#: minarca_client/ui/backup_settings.py:26
msgid "Back"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:30
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_patterns.py:23
#: minarca_client/ui/backup_restore_date.py:25
#: minarca_client/ui/backup_settings.py:26
msgid "Next"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:30
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_settings.py:26
msgid "Delete backup settings"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:275
#, python-format
msgid "%s Drive with %s available space"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:277
#, python-format
msgid " • Format %s"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:286
msgid ""
"Detected as a fixed device. Prefer using removable or network storage to "
"avoid data loss."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:288
msgid ""
"Ensure this network location is configured to automatically reconnect to "
"avoid data loss."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:290
msgid "FAT32 file system is not recommended for backup."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:292
msgid "Samba share over Gnome Virtual File system is not compatible."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:294
msgid ""
"NTFS isn't recommended on Linux due to remount issues after improper "
"unmounting."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:297
msgid "Available disk space at this location is limited."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:425
msgid "You don't have permissions to write at this location."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:431
msgid "Destination already exists"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:432
#: minarca_client/ui/backup_connection_remote.py:286
msgid "Do you want to replace the existing repository?"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:433
msgid ""
"The selected destination already exists at this location. If you continue"
" with this repository, you will replace its content using this computer. "
msgstr ""

#: minarca_client/ui/backup_connection_local.py:447
msgid "Unknown problem occurred when trying to configure the destination."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:477
msgid "Please wait. Scanning for removable disks..."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:488
msgid ""
"Please choose an external device or network share as your backup "
"destination."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:499
#: minarca_client/ui/backup_connection_local.py:500
msgid "Unable to retrieve information from selected location"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:501
msgid ""
"Unable to obtain detailed information on the selected location. Please "
"ensure that this location is accessible and valid. If the problem "
"persists, consult the application log with your administrator."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:525
msgid "Please wait. Initializing backup..."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:537
#: minarca_client/ui/backup_connection_remote.py:253
#: minarca_client/ui/backup_settings.py:428
msgid "Are you sure?"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:538
msgid "Are you sure you want to delete this backup configuration?"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:539
msgid ""
"If you delete this backup configuration, this Minarca agent will erase "
"its identity and will no longer run backup on schedule."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Provide your login details to configure remote backup."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Edit server connection"
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Address (IP or domain)"
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Username"
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Password"
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:243
msgid "Please wait. Initializing backup on remote server..."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:254
#: minarca_client/ui/backup_settings.py:429
msgid "Are you sure you want to forget these backup settings?"
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:255
#: minarca_client/ui/backup_settings.py:430
msgid "If you forget these settings, the backup will no longer run on schedule."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:285
msgid "Repository name already exists"
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:287
msgid ""
"The repository name you have entered already exists on the remote server."
" If you continue with this repository, you will replace its content using"
" this computer. Otherwise, you must enter a different repository name."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:302
msgid "Failed to establish connectivity with remote server."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:306
msgid "Unknown problem occured when connecting to the remote server."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:307
#, python-format
msgid ""
"An error occurred during the connection to Minarca server.\n"
"\n"
"Details: %s"
msgstr ""

#: minarca_client/ui/backup_create.py:11
msgid "Create a backup"
msgstr ""

#: minarca_client/ui/backup_create.py:11
msgid "Dedicated centralized server"
msgstr ""

#: minarca_client/ui/backup_create.py:11
msgid "Accessible anywhere"
msgstr ""

#: minarca_client/ui/backup_create.py:11
msgid "Remote backup"
msgstr ""

#: minarca_client/ui/backup_create.py:11
msgid "Setup"
msgstr ""

#: minarca_client/ui/backup_create.py:11
msgid "External disk or network share"
msgstr ""

#: minarca_client/ui/backup_create.py:11
msgid "Offline accessibility"
msgstr ""

#: minarca_client/ui/backup_create.py:11
msgid "Standalone backup"
msgstr ""

#: minarca_client/ui/backup_logs.py:26
msgid "Get detailed information about your last backup or restore operation."
msgstr ""

#: minarca_client/ui/backup_logs.py:26
msgid "Open file in text editor..."
msgstr ""

#: minarca_client/ui/backup_logs.py:26
msgid "Scroll to bottom"
msgstr ""

#: minarca_client/ui/backup_logs.py:256
msgid "No log"
msgstr ""

#: minarca_client/ui/backup_logs.py:262
msgid "Restore logs"
msgstr ""

#: minarca_client/ui/backup_logs.py:263
msgid "Backup logs"
msgstr ""

#: minarca_client/ui/backup_logs.py:270
#, python-format
msgid "Backup in progress for %s..."
msgstr ""

#: minarca_client/ui/backup_logs.py:272
#, python-format
msgid "Data restoration in progress for %s..."
msgstr ""

#: minarca_client/ui/backup_logs.py:307
#, python-format
msgid "The last backup ended with the following error: %s"
msgstr ""

#: minarca_client/ui/backup_logs.py:309
#, python-format
msgid "The last restoration ended with the following error: %s"
msgstr ""

#: minarca_client/ui/backup_logs.py:332
msgid "Confirmation Required"
msgstr ""

#: minarca_client/ui/backup_logs.py:333
msgid "Are you sure you want to stop the ongoing backup/restore process?"
msgstr ""

#: minarca_client/ui/backup_logs.py:334
msgid ""
"Your data may be incomplete or corrupted if the operation is terminated "
"prematurely. Please confirm your decision before proceeding."
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Select the files and folders you want to back up."
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "File Selection"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Files included"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Files excluded"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
#: minarca_client/ui/backup_patterns.py:267
msgid "Add file"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Exclude file"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
#: minarca_client/ui/backup_patterns.py:256
msgid "Add folder"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Exclude folder"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "File extention (e.g.: *.txt)"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Exclude"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Restore to default"
msgstr ""

#: minarca_client/ui/backup_restore_date.py:25
msgid "Choose the point in time of data to be restored."
msgstr ""

#: minarca_client/ui/backup_restore_date.py:25
msgid "Select date & Time"
msgstr ""

#: minarca_client/ui/backup_restore_date.py:172
msgid "Please wait. Loading backup dates..."
msgstr ""

#: minarca_client/ui/backup_restore_date.py:180
msgid "Failed to retrieve available backup dates."
msgstr ""

#: minarca_client/ui/backup_restore_date.py:184
msgid "Unknown problem occurred when collecting backup dates."
msgstr ""

#: minarca_client/ui/backup_restore_files.py:28
msgid ""
"When you perform a custom restore, the selected item is restored to a "
"different location selected by you."
msgstr ""

#: minarca_client/ui/backup_restore_files.py:28
msgid "Search for files or folders..."
msgstr ""

#: minarca_client/ui/backup_restore_files.py:28
msgid ""
"Restore files in-place, replacing existing files. I understand this may "
"overwrite data if the destination isn't empty."
msgstr ""

#: minarca_client/ui/backup_restore_files.py:28
msgid "Restore..."
msgstr ""

#: minarca_client/ui/backup_restore_files.py:211
msgid "Please wait. Getting file list..."
msgstr ""

#: minarca_client/ui/backup_restore_files.py:231
msgid "Failed to retrieve available files."
msgstr ""

#: minarca_client/ui/backup_restore_files.py:235
msgid "Unknown problem occurred when collecting file list."
msgstr ""

#: minarca_client/ui/backup_restore_files.py:259
#, python-format
msgid "%s item selected: %s"
msgid_plural "%s items selected: %s"
msgstr[0] ""
msgstr[1] ""

#: minarca_client/ui/backup_restore_files.py:260
msgid "No item selected"
msgstr ""

#: minarca_client/ui/backup_restore_files.py:284
msgid "Confirm In-Place Restoration"
msgstr ""

#: minarca_client/ui/backup_restore_files.py:285
msgid "Are you sure you want to run a full restoration?"
msgstr ""

#: minarca_client/ui/backup_restore_files.py:286
msgid ""
"This action will overwrite all existing files selected with the previous "
"version present in the backup. This action is irreversible and may result"
" in data loss if the destination is not empty."
msgstr ""

#: minarca_client/ui/backup_restore_files.py:296
msgid "Select a folder where to restore data."
msgstr ""

#: minarca_client/ui/backup_settings.py:26
msgid "Configure your backup settings for personalized data protection."
msgstr ""

#: minarca_client/ui/backup_settings.py:26
msgid "Backup frequency"
msgstr ""

#: minarca_client/ui/backup_settings.py:26
msgid "Run whether the user's session is open or not"
msgstr ""

#: minarca_client/ui/backup_settings.py:26
msgid "Excluded Days of the Week"
msgstr ""

#: minarca_client/ui/backup_settings.py:26
msgid "Monday"
msgstr ""

#: minarca_client/ui/backup_settings.py:26
msgid "Tuesday"
msgstr ""

#: minarca_client/ui/backup_settings.py:26
msgid "Wednesday"
msgstr ""

#: minarca_client/ui/backup_settings.py:26
msgid "Thrusday"
msgstr ""

#: minarca_client/ui/backup_settings.py:26
msgid "Friday"
msgstr ""

#: minarca_client/ui/backup_settings.py:26
msgid "Saturday"
msgstr ""

#: minarca_client/ui/backup_settings.py:26
msgid "Sunday"
msgstr ""

#: minarca_client/ui/backup_settings.py:26
msgid "Data Retention Duration"
msgstr ""

#: minarca_client/ui/backup_settings.py:26
msgid "Inactivity Notification Period"
msgstr ""

#: minarca_client/ui/backup_settings.py:228
msgid "Please wait. Loading backup settings..."
msgstr ""

#: minarca_client/ui/backup_settings.py:251
msgid "Manual"
msgstr ""

#: minarca_client/ui/backup_settings.py:251
msgid "Hourly"
msgstr ""

#: minarca_client/ui/backup_settings.py:251
msgid "Four times a day"
msgstr ""

#: minarca_client/ui/backup_settings.py:251
msgid "Twice a day"
msgstr ""

#: minarca_client/ui/backup_settings.py:251
msgid "Once a day"
msgstr ""

#: minarca_client/ui/backup_settings.py:258
#: minarca_client/ui/backup_settings.py:277
msgid "1 day"
msgstr ""

#: minarca_client/ui/backup_settings.py:259
#: minarca_client/ui/backup_settings.py:278
msgid "2 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:260
#: minarca_client/ui/backup_settings.py:279
msgid "3 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:261
#: minarca_client/ui/backup_settings.py:280
msgid "4 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:262
#: minarca_client/ui/backup_settings.py:281
msgid "5 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:263
#: minarca_client/ui/backup_settings.py:282
msgid "6 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:264
#: minarca_client/ui/backup_settings.py:283
msgid "1 week"
msgstr ""

#: minarca_client/ui/backup_settings.py:265
#: minarca_client/ui/backup_settings.py:284
msgid "2 weeks"
msgstr ""

#: minarca_client/ui/backup_settings.py:266
#: minarca_client/ui/backup_settings.py:285
msgid "3 weeks"
msgstr ""

#: minarca_client/ui/backup_settings.py:267
msgid "4 weeks"
msgstr ""

#: minarca_client/ui/backup_settings.py:268
#: minarca_client/ui/backup_settings.py:286
msgid "1 month"
msgstr ""

#: minarca_client/ui/backup_settings.py:276
msgid "Forever"
msgstr ""

#: minarca_client/ui/backup_settings.py:287
msgid "2 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:288
msgid "3 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:289
msgid "4 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:290
msgid "5 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:291
msgid "6 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:292
msgid "7 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:293
msgid "8 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:294
msgid "9 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:295
msgid "10 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:296
msgid "11 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:297
msgid "1 year"
msgstr ""

#: minarca_client/ui/backup_settings.py:298
msgid "2 years"
msgstr ""

#: minarca_client/ui/backup_settings.py:299
msgid "3 years"
msgstr ""

#: minarca_client/ui/backup_settings.py:300
msgid "4 years"
msgstr ""

#: minarca_client/ui/backup_settings.py:301
msgid "5 years"
msgstr ""

#: minarca_client/ui/backup_settings.py:321
msgid "Unable to retrieve settings from remote server."
msgstr ""

#: minarca_client/ui/backup_settings.py:322
msgid ""
"This issue may arise due to the remote server being out-of-date. You may "
"edit the settings, however, some settings will not be synchronized with "
"the remote server. If this problem persists, we recommend contacting your"
" administrator for further assistance."
msgstr ""

#: minarca_client/ui/backup_settings.py:330
msgid "Unable to retrieve configuration from remote server."
msgstr ""

#: minarca_client/ui/backup_settings.py:331
#, python-format
msgid ""
"An error occurred during the connection.\n"
"\n"
"Details: %s"
msgstr ""

#: minarca_client/ui/backup_settings.py:380
msgid "Repository not found"
msgstr ""

#: minarca_client/ui/backup_settings.py:381
#: minarca_client/ui/backup_settings.py:403
msgid "A problem occured while trying to save the backup settings."
msgstr ""

#: minarca_client/ui/backup_settings.py:387
msgid "Authentication failed"
msgstr ""

#: minarca_client/ui/backup_settings.py:388
msgid ""
"Your settings could not be saved to remote server. Do you want to "
"continue ?"
msgstr ""

#: minarca_client/ui/backup_settings.py:389
msgid ""
"This issue may arise due to the remote server being out-of-date. You have"
" the option to proceed, however, some settings will not be synchronized "
"with the remote server. If this problem persists, we recommend contacting"
" your administrator for further assistance."
msgstr ""

#: minarca_client/ui/backup_settings.py:402
msgid "Save Settings timeout"
msgstr ""

#: minarca_client/ui/backup_settings.py:404
msgid ""
"The operation timeout. Check your internet connection and verify if the "
"remote server is online. If the problem persist contact your "
"administrator."
msgstr ""

#: minarca_client/ui/backup_settings.py:412
msgid "Cannot save settings"
msgstr ""

#: minarca_client/ui/backup_settings.py:413
msgid ""
"An unknown problem occured while trying to save the backup settings. If "
"the problem persist contact your administrator."
msgstr ""

#: minarca_client/ui/backup_settings.py:462
msgid "Windows Credentials"
msgstr ""

#: minarca_client/ui/backup_settings.py:462
msgid "Enter credentials for local machine:"
msgstr ""

#: minarca_client/ui/backup_settings.py:467
msgid "Cannot apply your changes."
msgstr ""

#: minarca_client/ui/backup_settings.py:471
msgid "Backup Configuration"
msgstr ""

#: minarca_client/ui/dashboard.py:17
msgid "Dashboard"
msgstr ""

#: minarca_client/ui/dashboard.py:17
msgid "Setup backup"
msgstr ""

#: minarca_client/ui/side_pannel.py:98
msgid "Create an online backup"
msgstr ""

#: minarca_client/ui/side_pannel.py:100
msgid "Online restore"
msgstr ""

#: minarca_client/ui/side_pannel.py:105
msgid "Create a local backup"
msgstr ""

#: minarca_client/ui/side_pannel.py:107
msgid "Local restore"
msgstr ""

