# Translations template for minarca_client.
# Copyright (C) 2024 ORGANIZATION
# This file is distributed under the same license as the minarca_client project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2024.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: minarca_client 6.0.0rc2.dev1+g269140a.d20240822\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2024-08-22 10:57-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.14.0\n"

#: minarca_client/main.py:53
msgid "Operation aborted by the user."
msgstr ""

#: minarca_client/main.py:62
msgid "yes"
msgstr ""

#: minarca_client/main.py:62
msgid "y"
msgstr ""

#: minarca_client/main.py:71
#, python-format
msgid "new version %s available"
msgstr ""

#: minarca_client/main.py:73
msgid "fail to check for latest version"
msgstr ""

#: minarca_client/main.py:87
msgid "unexpected error during backup"
msgstr ""

#: minarca_client/main.py:94
msgid "Backup Instances:"
msgstr ""

#: minarca_client/main.py:96 minarca_client/main.py:406
#: minarca_client/ui/backup_card.py:21
msgid "No name"
msgstr ""

#: minarca_client/main.py:98
msgid "Are you sure you want to forget the above backup settings? (Yes/No): "
msgstr ""

#: minarca_client/main.py:116
msgid ""
"Do you want to backup to a local device (external disk or network share)? "
"(Yes/No): "
msgstr ""

#: minarca_client/main.py:122
msgid "Enter the local destination path: "
msgstr ""

#: minarca_client/main.py:142
msgid "Remote URL (e.g.: https://backup.examples.com): "
msgstr ""

#: minarca_client/main.py:144
msgid "Username: "
msgstr ""

#: minarca_client/main.py:146
msgid "Password or access token: "
msgstr ""

#: minarca_client/main.py:163 minarca_client/main.py:168
msgid "Linked successfully"
msgstr ""

#: minarca_client/main.py:166
msgid "Do you want to replace the existing repository? (Yes/No): "
msgstr ""

#: minarca_client/main.py:180
msgid ""
"A problem prevents the automatic scheduling of backup jobs. As a result, your"
" backup tasks cannot be executed as planned."
msgstr ""

#: minarca_client/main.py:189
msgid ""
"To update include or exclude patterns, you must configure at least one backup"
" instance."
msgstr ""

#: minarca_client/main.py:267
msgid "From which backup source do you want to restore data from?"
msgstr ""

#: minarca_client/main.py:279
msgid "Enter backup instance ID: "
msgstr ""

#: minarca_client/main.py:283
#, python-format
msgid "Invalid instance ID: %s"
msgstr ""

#: minarca_client/main.py:287
msgid "Your instance value doesn't match any backup instances"
msgstr ""

#: minarca_client/main.py:289
msgid "Your instance value matches too many backup instances"
msgstr ""

#: minarca_client/main.py:302
#, python-format
msgid "Do you want to restore %s? (Yes/No): "
msgstr ""

#: minarca_client/main.py:316
msgid ""
"Are you sure you want to proceed with the restore operation? Please note that"
" this will override your current data. (Yes/No): "
msgstr ""

#: minarca_client/main.py:340
msgid "backup not running"
msgstr ""

#: minarca_client/main.py:406
#, python-format
msgid "Backup Instance: %s"
msgstr ""

#: minarca_client/main.py:410
#, python-format
msgid "Identifier:             %s"
msgstr ""

#: minarca_client/main.py:412
#, python-format
msgid "Remote server:          %s"
msgstr ""

#: minarca_client/main.py:414
#, python-format
msgid "Local device:           %s"
msgstr ""

#: minarca_client/main.py:415
#, python-format
msgid "Connectivity status:    %s"
msgstr ""

#: minarca_client/main.py:415
msgid "Connected"
msgstr ""

#: minarca_client/main.py:415
msgid "Not connected"
msgstr ""

#: minarca_client/main.py:418
#, python-format
msgid "Last successful backup: %s"
msgstr ""

#: minarca_client/main.py:419 minarca_client/main.py:424 minarca_client/main.py:426
#: minarca_client/ui/backup_settings.py:253
msgid "Never"
msgstr ""

#: minarca_client/main.py:423
#, python-format
msgid "Last backup date:       %s"
msgstr ""

#: minarca_client/main.py:426
#, python-format
msgid "Last backup status:     %s"
msgstr ""

#: minarca_client/main.py:428
#, python-format
msgid "Details:                %s"
msgstr ""

#: minarca_client/main.py:430
#, python-format
msgid "Paused until:           %s"
msgstr ""

#: minarca_client/main.py:455
msgid "Minarca"
msgstr ""

#: minarca_client/main.py:456
msgid "Application failed to start"
msgstr ""

#: minarca_client/main.py:457
msgid ""
"If the problem persists, check the logs with your administrator or try "
"reinstalling the application."
msgstr ""

#: minarca_client/main.py:478
msgid ""
"Minarca manages your computer's backup by linking your computer with a "
"centralized server and running backups on a given schedule."
msgstr ""

#: minarca_client/main.py:497
msgid "start a backup in background mode"
msgstr ""

#: minarca_client/main.py:498 minarca_client/main.py:510
msgid "force execution of a backup even if it's not time to run"
msgstr ""

#: minarca_client/main.py:502 minarca_client/main.py:514
msgid "Limit backup to the given instance(s)."
msgstr ""

#: minarca_client/main.py:509
msgid "start a backup in foreground mode"
msgstr ""

#: minarca_client/main.py:521
msgid "exclude files from being backed up"
msgstr ""

#: minarca_client/main.py:525
msgid "Add exclude file pattern to the given instance(s)."
msgstr ""

#: minarca_client/main.py:529 minarca_client/main.py:542
msgid "file pattern to be excluded. May contain `*` or `?` wildcard"
msgstr ""

#: minarca_client/main.py:534
msgid "include files to be backed up"
msgstr ""

#: minarca_client/main.py:538
msgid "Add include file pattern to the given instance(s)."
msgstr ""

#: minarca_client/main.py:548
msgid "configure this agent to backup to a new destination (remote or local)"
msgstr ""

#: minarca_client/main.py:550
msgid "URL to the remote server. e.g.: http://example.com:8080/"
msgstr ""

#: minarca_client/main.py:551
msgid "username to be used for authentication with the remote server"
msgstr ""

#: minarca_client/main.py:555
msgid ""
"password or access token to use for authentication. You will be prompted if "
"not provided"
msgstr ""

#: minarca_client/main.py:557
msgid "repository name to be used"
msgstr ""

#: minarca_client/main.py:561
msgid ""
"replace existing repository on backup destination if it exists without "
"confirmation"
msgstr ""

#: minarca_client/main.py:563
msgid "path to local destination"
msgstr ""

#: minarca_client/main.py:567
msgid "list the include/exclude patterns"
msgstr ""

#: minarca_client/main.py:571
msgid "Show include and exclude patterns only for the given instance(s)."
msgstr ""

#: minarca_client/main.py:578
msgid "restore data from backup"
msgstr ""

#: minarca_client/main.py:582
msgid "Force the use of a given instance for restore."
msgstr ""

#: minarca_client/main.py:588
msgid ""
"Date and time to be restored. Could be 'now' to restore the latest backup. "
"Could be an epoch value like '1682367069'. Could be an ISO date format like "
"'2023-02-24T04:11:09-04:00'. Could be an interval like '3D' for 3 days ago."
msgstr ""

#: minarca_client/main.py:594
msgid ""
"Define an alternate location to restore files or folders instead of restoring"
" them in place."
msgstr ""

#: minarca_client/main.py:599
msgid "Force execution of restore operation without confirmation from the user."
msgstr ""

#: minarca_client/main.py:601
msgid "files and folders to be restored"
msgstr ""

#: minarca_client/main.py:605
msgid "stop the backup"
msgstr ""

#: minarca_client/main.py:609
msgid "Stop only the given instance(s)."
msgstr ""

#: minarca_client/main.py:613
msgid "doesn't fail if the backup is not running."
msgstr ""

#: minarca_client/main.py:618
msgid "create the required scheduled task in crontab or Windows Task Scheduler"
msgstr ""

#: minarca_client/main.py:625
msgid "schedule backup to run hourly"
msgstr ""

#: minarca_client/main.py:632
msgid "schedule backup to run daily"
msgstr ""

#: minarca_client/main.py:639
msgid "schedule backup to run weekly"
msgstr ""

#: minarca_client/main.py:644
msgid "Configure only the given instance(s)."
msgstr ""

#: minarca_client/main.py:649
msgid "username required to run task when the user is logged out"
msgstr ""

#: minarca_client/main.py:650
msgid "password required to run task when the user is logged out"
msgstr ""

#: minarca_client/main.py:654
msgid "return the current Minarca status"
msgstr ""

#: minarca_client/main.py:658
msgid "Show status for the given instance(s)."
msgstr ""

#: minarca_client/main.py:665
msgid "forget backup settings"
msgstr ""

#: minarca_client/main.py:669
msgid "Forget settings of the given backup instance(s)."
msgstr ""

#: minarca_client/main.py:674
msgid "Force forget operation without confirmation from the user."
msgstr ""

#: minarca_client/main.py:681
msgid ""
"temporarily delay the execution of the backup for the given number of hours. "
"Default is 24 hours."
msgstr ""

#: minarca_client/main.py:686
msgid "Pause only the given instance(s)."
msgstr ""

#: minarca_client/main.py:690
msgid "number of hours"
msgstr ""

#: minarca_client/main.py:695
msgid "clear previously set delay"
msgstr ""

#: minarca_client/main.py:704
msgid "verify backup integrity"
msgstr ""

#: minarca_client/main.py:708
msgid "Verify backup integrity of the given backup instance(s)."
msgstr ""

#: minarca_client/main.py:715
msgid "open graphical user interface (default when calling minarcaw)"
msgstr ""

#: minarca_client/main.py:786
msgid "Process interrupted by user."
msgstr ""

#: minarca_client/core/compat.py:385
msgid "Minarca Backup"
msgstr ""

#: minarca_client/core/compat.py:440
msgid ""
"Keeps your Minarca Backup Software running. If this task is disabled or "
"stopped, your Minarca backup will stop working. This task gets created when "
"linking Minarca with a central backup server. When installing Minarca on a "
"Windows Server, it's preferable to change the settings of this task and "
"select 'Run whether user is logged on or not' to make sure the backup is "
"running even when nobody is using the server."
msgstr ""

#: minarca_client/core/config.py:327
msgid "User's Documents"
msgstr ""

#: minarca_client/core/config.py:329
msgid "Minarca Config"
msgstr ""

#: minarca_client/core/config.py:334
msgid "Thumbnails cache"
msgstr ""

#: minarca_client/core/config.py:335
msgid "Arrangement of a Windows folder"
msgstr ""

#: minarca_client/core/config.py:336
msgid "Swap System File"
msgstr ""

#: minarca_client/core/config.py:337
msgid "Page System File"
msgstr ""

#: minarca_client/core/config.py:338
msgid "Hibernation System File"
msgstr ""

#: minarca_client/core/config.py:339
msgid "System Volume Information"
msgstr ""

#: minarca_client/core/config.py:340
msgid "System Recovery"
msgstr ""

#: minarca_client/core/config.py:341
msgid "Recycle bin"
msgstr ""

#: minarca_client/core/config.py:342 minarca_client/core/config.py:368
msgid "Temporary Folder"
msgstr ""

#: minarca_client/core/config.py:343
msgid "AutoCAD backup files"
msgstr ""

#: minarca_client/core/config.py:344
msgid "Office temporary files"
msgstr ""

#: minarca_client/core/config.py:345
msgid "Outlook IMAP temporary files"
msgstr ""

#: minarca_client/core/config.py:346
msgid "Outlook POP temporary files"
msgstr ""

#: minarca_client/core/config.py:347
msgid "Google Drive temporary upload files"
msgstr ""

#: minarca_client/core/config.py:348
msgid "Google Drive temporary download files"
msgstr ""

#: minarca_client/core/config.py:352
msgid "OneDrive GUID File"
msgstr ""

#: minarca_client/core/config.py:359
msgid "Desktop Services Store"
msgstr ""

#: minarca_client/core/config.py:365
msgid "dev filesystem"
msgstr ""

#: minarca_client/core/config.py:366
msgid "proc filesystem"
msgstr ""

#: minarca_client/core/config.py:367
msgid "sys filesystem"
msgstr ""

#: minarca_client/core/config.py:369
msgid "Volatile program files"
msgstr ""

#: minarca_client/core/config.py:370
msgid "Mounted filesystems"
msgstr ""

#: minarca_client/core/config.py:371
msgid "External media"
msgstr ""

#: minarca_client/core/config.py:372
msgid "Ext4 Lost and Found"
msgstr ""

#: minarca_client/core/config.py:373
msgid "Hidden temporary files"
msgstr ""

#: minarca_client/core/config.py:374
msgid "Vim temporary files"
msgstr ""

#: minarca_client/core/exceptions.py:71
#, python-format
msgid "No backup instances match: %s"
msgstr ""

#: minarca_client/core/exceptions.py:82
#, python-format
msgid "Destination `%s` already exists."
msgstr ""

#: minarca_client/core/exceptions.py:92
msgid ""
"These settings conflict with an existing backup and therefore cannot be "
"created."
msgstr ""

#: minarca_client/core/exceptions.py:93
msgid ""
"It is not possible to create two backups with the same destination settings. "
"These will conflict during backup. Be sure to define a different destination "
"for this backup."
msgstr ""

#: minarca_client/core/exceptions.py:108
#, python-format
msgid ""
"your file specification [%s] doesn't match any of the base directories of "
"your system"
msgstr ""

#: minarca_client/core/exceptions.py:118
#, python-format
msgid "process terminated with an exception. Check logs for more details: %s"
msgstr ""

#: minarca_client/core/exceptions.py:126
msgid "process returned a non-zero exit status. Check logs for more details"
msgstr ""

#: minarca_client/core/exceptions.py:134
#: minarca_client/core/tests/test_instance.py:629
msgid "No files included in backup. Check configuration."
msgstr ""

#: minarca_client/core/exceptions.py:142
msgid "cannot stop process when it's not running."
msgstr ""

#: minarca_client/core/exceptions.py:150
msgid "cannot start process when it's already running."
msgstr ""

#: minarca_client/core/exceptions.py:158
msgid "not configured, use `minarca configure` to configure remote host"
msgstr ""

#: minarca_client/core/exceptions.py:166
msgid "backup not yet scheduled to run. You may force execution using `--force`"
msgstr ""

#: minarca_client/core/exceptions.py:175
msgid "Cannot establish connection to remote server."
msgstr ""

#: minarca_client/core/exceptions.py:177
#, python-format
msgid ""
"Your computer cannot establish a connection to the remote server. Make sure "
"your Internet connection is working and that the following URL is accessible "
"with a Web browser: %s"
msgstr ""

#: minarca_client/core/exceptions.py:190
msgid "Invalid remote server URL!"
msgstr ""

#: minarca_client/core/exceptions.py:191
msgid ""
"The remote server URL you entered for the connection is not valid. Check that"
" you have entered the correct value. The URL must begin with `http://` or "
"`https://` followed by a domain name."
msgstr ""

#: minarca_client/core/exceptions.py:203
msgid "Invalid username or password"
msgstr ""

#: minarca_client/core/exceptions.py:204
msgid ""
"The username or password you entered to connect to the remote server is not "
"valid. If you have enabled multi-factor authentication, you need to use an "
"access token."
msgstr ""

#: minarca_client/core/exceptions.py:219
msgid "The remote server returned an error. You may try again later."
msgstr ""

#: minarca_client/core/exceptions.py:228
msgid ""
"Unable to connect to the remote server. The problem may be with the remote "
"server. If the problem persists, contact your system administrator to check "
"the SSH server configuration and a possible firewall blocking the connection."
msgstr ""

#: minarca_client/core/exceptions.py:243
msgid ""
"The connection to the remote server failed because our identity was refused. "
"The problem may lie with the remote server. If the problem persists, contact "
"your system administrator to check your SSH identity."
msgstr ""

#: minarca_client/core/exceptions.py:257
msgid ""
"The connection to the remote server cannot be established securely because "
"the server's identity has changed. If the problem persists, contact your "
"system administrator to verify the server's identity."
msgstr ""

#: minarca_client/core/exceptions.py:271
msgid ""
"Backup failed due to disk quota exceeded. Please free up disk space to ensure"
" successful backup."
msgstr ""

#: minarca_client/core/exceptions.py:283
msgid ""
"Backup failed due to disk being full. Please clear space on the disk to "
"proceed with the backup."
msgstr ""

#: minarca_client/core/exceptions.py:295
msgid ""
"The connection to the remote server has failed due to an unresolvable host "
"name. Please check your network connection and ensure that the host name is "
"still valid. If the problem persists, contact your system administrator to "
"check the host name."
msgstr ""

#: minarca_client/core/exceptions.py:309
msgid ""
"The connection to the remote server has failed due to an unsupported version "
"of the Minarca agent on the remote server. Consider updating your agent or "
"server."
msgstr ""

#: minarca_client/core/exceptions.py:319
msgid "The path you are trying to restore from backup does not exist."
msgstr ""

#: minarca_client/core/exceptions.py:327
msgid "Another backup session is currently in progress on the remote server."
msgstr ""

#: minarca_client/core/exceptions.py:335
msgid ""
"An internal error was raised by an unknown operation sent to the background "
"process."
msgstr ""

#: minarca_client/core/exceptions.py:347
msgid "Backup Destination Occupied"
msgstr ""

#: minarca_client/core/exceptions.py:348
msgid ""
"Unable to proceed with the selected destination as it contains existing data."
" If you intend to use this location, kindly empty the directory of any files "
"and folders."
msgstr ""

#: minarca_client/core/exceptions.py:358
msgid "Destination Not Suitable"
msgstr ""

#: minarca_client/core/exceptions.py:359
msgid ""
"Unable to proceed with the selected destination as it cannot be initialized. "
"Make sure the external device is connected and operational."
msgstr ""

#: minarca_client/core/exceptions.py:369
msgid ""
"Backup Destination Not Found. Please ensure that your external disk or "
"network share is properly connected and accessible."
msgstr ""

#: minarca_client/core/exceptions.py:375
msgid ""
"Backup unsuccessful due to a copy operation encountering an issue, "
"potentially because the device is disconnected. Ensure your device is "
"properly connected."
msgstr ""

#: minarca_client/core/exceptions.py:389
msgid "Repository cannot be found on remote server"
msgstr ""

#: minarca_client/core/exceptions.py:394
#, python-format
msgid "Repository `%s` cannot be found on remote server"
msgstr ""

#: minarca_client/core/exceptions.py:410
msgid "Repository name must contain only letters, numbers, dashes (-), and dots (.)"
msgstr ""

#: minarca_client/core/instance.py:211
msgid "Your backup is outdated"
msgstr ""

#: minarca_client/core/instance.py:212
#, python-format
msgid ""
"Your backup %s is outdated by over %s days. Please plug in your local device "
"and run the backup."
msgstr ""

#: minarca_client/core/latest.py:31
msgid "https://minarca.org/download/"
msgstr ""

#: minarca_client/core/notification/_notification_win.py:127
msgid "Show details"
msgstr ""

#: minarca_client/dialogs/_dialogs_cocoa.py:72
msgid "Yes"
msgstr ""

#: minarca_client/dialogs/_dialogs_cocoa.py:72
msgid "No"
msgstr ""

#: minarca_client/ui/about_menu.py:20
#: minarca_client/ui/backup_connection_local.py:27
msgid "Browse"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Settings"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Get Help"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Help"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Website"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Minarca Agent"
msgstr ""

#: minarca_client/ui/about_menu.py:20
#, python-format
msgid "Version %s"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Update now"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Copyright © 2024 IKUS Software"
msgstr ""

#: minarca_client/ui/about_menu.py:126 minarca_client/ui/about_menu.py:128
#: minarca_client/ui/backup_connection_local.py:237
#, python-format
msgid "%s on %s"
msgstr ""

#: minarca_client/ui/about_menu.py:226
msgid "Checking for updates..."
msgstr ""

#: minarca_client/ui/about_menu.py:228
msgid "Unable to verify update availability at this time."
msgstr ""

#: minarca_client/ui/about_menu.py:230
#, python-format
msgid "New version %s available"
msgstr ""

#: minarca_client/ui/about_menu.py:232
msgid "Current version is up-to-date"
msgstr ""

#: minarca_client/ui/backup_card.py:21 minarca_client/ui/backup_create.py:10
#: minarca_client/ui/side_pannel.py:101
msgid "Online backup"
msgstr ""

#: minarca_client/ui/backup_card.py:21 minarca_client/ui/backup_create.py:10
#: minarca_client/ui/side_pannel.py:108
msgid "Local backup"
msgstr ""

#: minarca_client/ui/backup_card.py:21
msgid "Paused"
msgstr ""

#: minarca_client/ui/backup_card.py:21
msgid "Active"
msgstr ""

#: minarca_client/ui/backup_card.py:21 minarca_client/ui/backup_settings.py:22
msgid "Backup configuration"
msgstr ""

#: minarca_client/ui/backup_card.py:21
#: minarca_client/ui/backup_restore_custom.py:30
#: minarca_client/ui/backup_restore_full.py:30
msgid "File selection"
msgstr ""

#: minarca_client/ui/backup_card.py:21
msgid "Restore backup"
msgstr ""

#: minarca_client/ui/backup_card.py:287
msgid "Calculating disk usage"
msgstr ""

#: minarca_client/ui/backup_card.py:289
msgid "Cannot determine disk usage"
msgstr ""

#: minarca_client/ui/backup_card.py:290
#, python-format
msgid "Used space %s"
msgstr ""

#: minarca_client/ui/backup_card.py:298
#, python-format
msgid "Total space %s"
msgstr ""

#: minarca_client/ui/backup_card.py:303
msgid "Stopping..."
msgstr ""

#: minarca_client/ui/backup_card.py:303
msgid "Starting..."
msgstr ""

#: minarca_client/ui/backup_card.py:308
msgid "Stop Restore"
msgstr ""

#: minarca_client/ui/backup_card.py:309
msgid "Stop Backup"
msgstr ""

#: minarca_client/ui/backup_card.py:311
msgid "Start Backup now"
msgstr ""

#: minarca_client/ui/backup_card.py:319 minarca_client/ui/backup_logs.py:268
msgid "No backup yet"
msgstr ""

#: minarca_client/ui/backup_card.py:323
msgid "Backup in progress..."
msgstr ""

#: minarca_client/ui/backup_card.py:324 minarca_client/ui/backup_logs.py:272
#, python-format
msgid "Last backup: %s"
msgstr ""

#: minarca_client/ui/backup_card.py:327
msgid "Restore in progress..."
msgstr ""

#: minarca_client/ui/backup_card.py:328 minarca_client/ui/backup_logs.py:274
#, python-format
msgid "Last restore: %s"
msgstr ""

#: minarca_client/ui/backup_card.py:335
#: minarca_client/ui/backup_connection_remote.py:21
msgid "Server connection"
msgstr ""

#: minarca_client/ui/backup_card.py:335
msgid "Local connection"
msgstr ""

#: minarca_client/ui/backup_card.py:379
msgid "Pause Backup Job Confirmation"
msgstr ""

#: minarca_client/ui/backup_card.py:380
msgid "Are you sure you want to pause the backup job?"
msgstr ""

#: minarca_client/ui/backup_card.py:381
msgid ""
"Pausing the backup job will temporarily suspend the ongoing backup process "
"for the next 24 hours. This action may affect the availability of recent data"
" restore points and introduce delays in the backup schedule. Please confirm "
"your intention before proceeding."
msgstr ""

#: minarca_client/ui/backup_card.py:400
msgid "Start Backup"
msgstr ""

#: minarca_client/ui/backup_card.py:401
msgid "A problem occurred when trying to start the backup process."
msgstr ""

#: minarca_client/ui/backup_card.py:402
msgid ""
"This usually indicate a problem with the installation. Try re-installing "
"Minarca Backup."
msgstr ""

#: minarca_client/ui/backup_card.py:416 minarca_client/ui/backup_logs.py:328
msgid "Stop process"
msgstr ""

#: minarca_client/ui/backup_card.py:417 minarca_client/ui/backup_logs.py:329
msgid "A problem occurred when trying to stop the process."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
msgid "Select a location to be used for backing up your data."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
msgid "Target location"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
msgid "Edit target location"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
#: minarca_client/ui/backup_connection_remote.py:21
msgid "Backup name"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
msgid "Refresh"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
msgid ""
"No external drive has been detected for data backup. Plug in your external "
"drive and click on the refresh button to update this list. If your device is "
"not on the list, check its connectivity and make sure it's switched on."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_create.py:10 minarca_client/ui/backup_logs.py:24
#: minarca_client/ui/backup_restore.py:16
#: minarca_client/ui/backup_restore_custom.py:30
#: minarca_client/ui/backup_restore_date.py:24
#: minarca_client/ui/backup_restore_full.py:30
#: minarca_client/ui/backup_settings.py:22
msgid "Back"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_patterns.py:23 minarca_client/ui/backup_settings.py:22
msgid "Cancel"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_patterns.py:23
#: minarca_client/ui/backup_restore_date.py:24
#: minarca_client/ui/backup_settings.py:22
msgid "Next"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_patterns.py:23 minarca_client/ui/backup_settings.py:22
msgid "Save"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_settings.py:22
msgid "Delete backup settings"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:250
#, python-format
msgid "%s Drive with %s available space"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:252
#, python-format
msgid " • Format %s"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:261
msgid ""
"Detected as a fixed device. Prefer using removable or network storage to "
"avoid data loss."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:263
msgid ""
"Ensure this network location is configured to automatically reconnect to "
"avoid data loss."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:265
msgid "FAT32 file system is not recommended for backup."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:267
msgid "Samba share over Gnome Virtual File system is not compatible."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:269
msgid ""
"NTFS isn't recommended on Linux due to remount issues after improper "
"unmounting."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:272
msgid "Available disk space at this location is limited."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:400
msgid "You don't have permissions to write at this location."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:406
msgid "Destination already exists"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:407
#: minarca_client/ui/backup_connection_remote.py:286
msgid "Do you want to replace the existing repository?"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:408
msgid ""
"The selected destination already exists at this location. If you continue "
"with this repository, you will replace its content using this computer. "
msgstr ""

#: minarca_client/ui/backup_connection_local.py:422
msgid "Unknown problem occurred when trying to configure the destination."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:450
msgid "Please wait. Scanning for removable disks..."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:460
msgid "Please choose an external device or network share as your backup destination."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:470
#: minarca_client/ui/backup_connection_local.py:471
msgid "Unable to retrieve information from selected location"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:472
msgid ""
"Unable to obtain detailed information on the selected location. Please ensure"
" that this location is accessible and valid. If the problem persists, consult"
" the application log with your administrator."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:496
msgid "Please wait. Initializing backup..."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:508
#: minarca_client/ui/backup_connection_remote.py:253
#: minarca_client/ui/backup_settings.py:422
msgid "Are you sure?"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:509
msgid "Are you sure you want to delete this backup configuration?"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:510
msgid ""
"If you delete this backup configuration, this Minarca agent will erase its "
"identity and will no longer run backup on schedule."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Provide your login details to configure remote backup."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Edit server connection"
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Address (IP or domain)"
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Username"
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Password"
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:243
msgid "Please wait. Initializing backup on remote server..."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:254
#: minarca_client/ui/backup_settings.py:423
msgid "Are you sure you want to forget these backup settings?"
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:255
#: minarca_client/ui/backup_settings.py:424
msgid "If you forget these settings, the backup will no longer run on schedule."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:285
msgid "Repository name already exists"
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:287
msgid ""
"The repository name you have entered already exists on the remote server. If "
"you continue with this repository, you will replace its content using this "
"computer. Otherwise, you must enter a different repository name."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:302
msgid "Failed to establish connectivity with remote server."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:306
msgid "Unknown problem occured when connecting to the remote server."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:307
#, python-format
msgid ""
"An error occurred during the connection to Minarca server.\n"
"\n"
"Details: %s"
msgstr ""

#: minarca_client/ui/backup_create.py:10
msgid "Create a backup"
msgstr ""

#: minarca_client/ui/backup_create.py:10
msgid "Dedicated centralized server"
msgstr ""

#: minarca_client/ui/backup_create.py:10
msgid "Accessible anywhere"
msgstr ""

#: minarca_client/ui/backup_create.py:10
msgid "Remote backup"
msgstr ""

#: minarca_client/ui/backup_create.py:10
msgid "Setup"
msgstr ""

#: minarca_client/ui/backup_create.py:10
msgid "External disk or network share"
msgstr ""

#: minarca_client/ui/backup_create.py:10
msgid "Offline accessibility"
msgstr ""

#: minarca_client/ui/backup_create.py:10
msgid "Standalone backup"
msgstr ""

#: minarca_client/ui/backup_logs.py:24
msgid "Get detailed information about your last backup or restore operation."
msgstr ""

#: minarca_client/ui/backup_logs.py:24
msgid "Open file in text editor..."
msgstr ""

#: minarca_client/ui/backup_logs.py:24
msgid "Scroll to bottom"
msgstr ""

#: minarca_client/ui/backup_logs.py:244
msgid "Restore logs"
msgstr ""

#: minarca_client/ui/backup_logs.py:245
msgid "Backup logs"
msgstr ""

#: minarca_client/ui/backup_logs.py:252
#, python-format
msgid "Backup in progress for %s..."
msgstr ""

#: minarca_client/ui/backup_logs.py:254
#, python-format
msgid "Data restoration in progress for %s..."
msgstr ""

#: minarca_client/ui/backup_logs.py:289
#, python-format
msgid "The last backup ended with the following error: %s"
msgstr ""

#: minarca_client/ui/backup_logs.py:291
#, python-format
msgid "The last restoration ended with the following error: %s"
msgstr ""

#: minarca_client/ui/backup_logs.py:314
msgid "Confirmation Required"
msgstr ""

#: minarca_client/ui/backup_logs.py:315
msgid "Are you sure you want to stop the ongoing backup/restore process?"
msgstr ""

#: minarca_client/ui/backup_logs.py:316
msgid ""
"Your data may be incomplete or corrupted if the operation is terminated "
"prematurely. Please confirm your decision before proceeding."
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Select the files and folders you want to back up."
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "File Selection"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Files included"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Files excluded"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23 minarca_client/ui/backup_patterns.py:265
msgid "Add file"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Exclude file"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23 minarca_client/ui/backup_patterns.py:254
msgid "Add folder"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Exclude folder"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "File extention (e.g.: *.txt)"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Exclude"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Restore to default"
msgstr ""

#: minarca_client/ui/backup_restore.py:16
msgid ""
"Choose between restoring all files in place or selecting specific files for "
"restoration."
msgstr ""

#: minarca_client/ui/backup_restore.py:16
msgid "Restore Options"
msgstr ""

#: minarca_client/ui/backup_restore.py:16
msgid "Custom restore"
msgstr ""

#: minarca_client/ui/backup_restore.py:16
msgid "Select file(s) to restore"
msgstr ""

#: minarca_client/ui/backup_restore.py:16
msgid "Select destination"
msgstr ""

#: minarca_client/ui/backup_restore.py:16
msgid "Ideal for quick recovery"
msgstr ""

#: minarca_client/ui/backup_restore.py:16
msgid "Full restore"
msgstr ""

#: minarca_client/ui/backup_restore.py:16
msgid "Restore all files"
msgstr ""

#: minarca_client/ui/backup_restore.py:16
msgid "Replace existing files"
msgstr ""

#: minarca_client/ui/backup_restore.py:16
msgid "Ideal for hardware failure"
msgstr ""

#: minarca_client/ui/backup_restore_custom.py:30
msgid ""
"When you perform a custom restore, the selected item is restored to a "
"different location selected by you."
msgstr ""

#: minarca_client/ui/backup_restore_custom.py:30
msgid "Search for files or folders..."
msgstr ""

#: minarca_client/ui/backup_restore_custom.py:30
msgid "Restore..."
msgstr ""

#: minarca_client/ui/backup_restore_custom.py:201
#: minarca_client/ui/backup_restore_full.py:173
msgid "Please wait. Getting file list..."
msgstr ""

#: minarca_client/ui/backup_restore_custom.py:218
#: minarca_client/ui/backup_restore_full.py:204
msgid "Failed to retrieve available files."
msgstr ""

#: minarca_client/ui/backup_restore_custom.py:222
#: minarca_client/ui/backup_restore_full.py:208
msgid "Unknown problem occurred when collecting file list."
msgstr ""

#: minarca_client/ui/backup_restore_custom.py:266
msgid "Select a folder where to restore data."
msgstr ""

#: minarca_client/ui/backup_restore_date.py:24
msgid "Choose the point in time of data to be restored."
msgstr ""

#: minarca_client/ui/backup_restore_date.py:24
msgid "Select date & Time"
msgstr ""

#: minarca_client/ui/backup_restore_date.py:173
msgid "Please wait. Loading backup dates..."
msgstr ""

#: minarca_client/ui/backup_restore_date.py:181
msgid "\"Failed to retrieve available backup dates."
msgstr ""

#: minarca_client/ui/backup_restore_date.py:185
msgid "Unknown problem occurred when collecting backup dates."
msgstr ""

#: minarca_client/ui/backup_restore_full.py:30
msgid ""
"When you perform a full restore, the selected items will be restored to their"
" original location on your device."
msgstr ""

#: minarca_client/ui/backup_restore_full.py:30
msgid ""
"I understand that full restore replaces existing files on my device and may "
"result in data loss if the destination is not empty."
msgstr ""

#: minarca_client/ui/backup_restore_full.py:30
msgid "Restore"
msgstr ""

#: minarca_client/ui/backup_restore_full.py:249
msgid "Confirm Full Restore"
msgstr ""

#: minarca_client/ui/backup_restore_full.py:250
msgid "Are you sure you want to run a full restoration?"
msgstr ""

#: minarca_client/ui/backup_restore_full.py:251
msgid ""
"This action will overwrite all existing files selected with the previous "
"version present in the backup. This action is irreversible and may result in "
"data loss."
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Configure your backup settings for personalized data protection."
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Backup frequency"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Run whether the user's session is open or not"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Excluded Days of the Week"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Monday"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Tuesday"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Wednesday"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Thrusday"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Friday"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Saturday"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Sunday"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Data Retention Duration"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Inactivity Notification Period"
msgstr ""

#: minarca_client/ui/backup_settings.py:224
msgid "Please wait. Loading backup settings..."
msgstr ""

#: minarca_client/ui/backup_settings.py:247
msgid "Hourly"
msgstr ""

#: minarca_client/ui/backup_settings.py:247
msgid "Four times a day"
msgstr ""

#: minarca_client/ui/backup_settings.py:247
msgid "Twice a day"
msgstr ""

#: minarca_client/ui/backup_settings.py:247
msgid "Once a day"
msgstr ""

#: minarca_client/ui/backup_settings.py:254
#: minarca_client/ui/backup_settings.py:273
msgid "1 day"
msgstr ""

#: minarca_client/ui/backup_settings.py:255
#: minarca_client/ui/backup_settings.py:274
msgid "2 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:256
#: minarca_client/ui/backup_settings.py:275
msgid "3 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:257
#: minarca_client/ui/backup_settings.py:276
msgid "4 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:258
#: minarca_client/ui/backup_settings.py:277
msgid "5 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:259
#: minarca_client/ui/backup_settings.py:278
msgid "6 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:260
#: minarca_client/ui/backup_settings.py:279
msgid "1 week"
msgstr ""

#: minarca_client/ui/backup_settings.py:261
#: minarca_client/ui/backup_settings.py:280
msgid "2 weeks"
msgstr ""

#: minarca_client/ui/backup_settings.py:262
#: minarca_client/ui/backup_settings.py:281
msgid "3 weeks"
msgstr ""

#: minarca_client/ui/backup_settings.py:263
msgid "4 weeks"
msgstr ""

#: minarca_client/ui/backup_settings.py:264
#: minarca_client/ui/backup_settings.py:282
msgid "1 month"
msgstr ""

#: minarca_client/ui/backup_settings.py:272
msgid "Forever"
msgstr ""

#: minarca_client/ui/backup_settings.py:283
msgid "2 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:284
msgid "3 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:285
msgid "4 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:286
msgid "5 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:287
msgid "6 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:288
msgid "7 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:289
msgid "8 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:290
msgid "9 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:291
msgid "10 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:292
msgid "11 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:293
msgid "1 year"
msgstr ""

#: minarca_client/ui/backup_settings.py:294
msgid "2 years"
msgstr ""

#: minarca_client/ui/backup_settings.py:295
msgid "3 years"
msgstr ""

#: minarca_client/ui/backup_settings.py:296
msgid "4 years"
msgstr ""

#: minarca_client/ui/backup_settings.py:297
msgid "5 years"
msgstr ""

#: minarca_client/ui/backup_settings.py:317
msgid "Unable to retrieve settings from remote server."
msgstr ""

#: minarca_client/ui/backup_settings.py:318
msgid ""
"This issue may arise due to the remote server being out-of-date. You may edit"
" the settings, however, some settings will not be synchronized with the "
"remote server. If this problem persists, we recommend contacting your "
"administrator for further assistance."
msgstr ""

#: minarca_client/ui/backup_settings.py:326
msgid "Unable to retrieve configuration from remote server."
msgstr ""

#: minarca_client/ui/backup_settings.py:327
#, python-format
msgid ""
"An error occurred during the connection.\n"
"\n"
"Details: %s"
msgstr ""

#: minarca_client/ui/backup_settings.py:346
msgid "Please wait. Saving settings..."
msgstr ""

#: minarca_client/ui/backup_settings.py:374
msgid "Repository not found"
msgstr ""

#: minarca_client/ui/backup_settings.py:375
#: minarca_client/ui/backup_settings.py:397
msgid "A problem occured while trying to save the backup settings."
msgstr ""

#: minarca_client/ui/backup_settings.py:381
msgid "Authentication failed"
msgstr ""

#: minarca_client/ui/backup_settings.py:382
msgid "Your settings could not be saved to remote server. Do you want to continue ?"
msgstr ""

#: minarca_client/ui/backup_settings.py:383
msgid ""
"This issue may arise due to the remote server being out-of-date. You have the"
" option to proceed, however, some settings will not be synchronized with the "
"remote server. If this problem persists, we recommend contacting your "
"administrator for further assistance."
msgstr ""

#: minarca_client/ui/backup_settings.py:396
msgid "Save Settings timeout"
msgstr ""

#: minarca_client/ui/backup_settings.py:398
msgid ""
"The operation timeout. Check your internet connection and verify if the "
"remote server is online. If the problem persist contact your administrator."
msgstr ""

#: minarca_client/ui/backup_settings.py:406
msgid "Cannot save settings"
msgstr ""

#: minarca_client/ui/backup_settings.py:407
msgid ""
"An unknown problem occured while trying to save the backup settings. If the "
"problem persist contact your administrator."
msgstr ""

#: minarca_client/ui/backup_settings.py:451
msgid "Windows Credentials"
msgstr ""

#: minarca_client/ui/backup_settings.py:451
msgid "Enter credentials for local machine:"
msgstr ""

#: minarca_client/ui/backup_settings.py:460
msgid "Minarca cannot apply your changes."
msgstr ""

#: minarca_client/ui/backup_settings.py:464
msgid ""
"The user account is unknown or the password is incorrect. Be sure to enter "
"your Windows credentials, not your Minarca credentials."
msgstr ""

#: minarca_client/ui/backup_settings.py:469
msgid "Backup Configuration"
msgstr ""

#: minarca_client/ui/dashboard.py:17
msgid "Dashboard"
msgstr ""

#: minarca_client/ui/dashboard.py:17
msgid "Setup backup"
msgstr ""

#: minarca_client/ui/side_pannel.py:97
msgid "Create an online backup"
msgstr ""

#: minarca_client/ui/side_pannel.py:99
msgid "Online restore"
msgstr ""

#: minarca_client/ui/side_pannel.py:104
msgid "Create a local backup"
msgstr ""

#: minarca_client/ui/side_pannel.py:106
msgid "Local restore"
msgstr ""

