# French translations for minarca_client.
# Copyright (C) 2025 IKUS Software
# This file is distributed under the same license as the minarca_client
# project.
# Patrik Dufresne <patrik@ikus-soft.com>, 2025.
#
msgid ""
msgstr ""
"Project-Id-Version: minarca_client 3.9.1.dev11+g4d5317c\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2025-04-30 11:23-0400\n"
"PO-Revision-Date: 2025-04-30 11:24-0400\n"
"Last-Translator: \n"
"Language-Team: fr <LL@li.org>\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"Generated-By: Babel 2.16.0\n"
"X-Generator: Poedit 3.2.2\n"

#: minarca_client/main.py:46
msgid "Operation aborted by the user."
msgstr "Opération interrompue par l'utilisateur."

#: minarca_client/main.py:55
msgid "yes"
msgstr "oui"

#: minarca_client/main.py:55
msgid "y"
msgstr "o"

#: minarca_client/main.py:66
#, python-format
msgid "new version %s available"
msgstr "nouvelle version %s disponible"

#: minarca_client/main.py:68
msgid "fail to check for latest version"
msgstr "impossible de vérifier pour la dernière version"

#: minarca_client/main.py:81
msgid "Backup Instances:"
msgstr "Instances de sauvegarde :"

#: minarca_client/main.py:83 minarca_client/main.py:356
#: minarca_client/ui/backup_card.py:21
msgid "No name"
msgstr "Sans nom"

#: minarca_client/main.py:85
msgid "Are you sure you want to forget the above backup settings? (Yes/No): "
msgstr ""
"Êtes-vous sûr de vouloir oublier les paramètres de sauvegarde ci-dessus ? (Oui/"
"Non) : "

#: minarca_client/main.py:108
msgid ""
"Do you want to backup to a local device (external disk or network share)? (Yes/"
"No): "
msgstr ""
"Souhaitez-vous effectuer une sauvegarde sur un périphérique local (disque "
"externe ou partage de réseau) ? (Oui/Non) : "

#: minarca_client/main.py:114
msgid "Enter the local destination path: "
msgstr "Saisir le chemin d'accès local de la destination : "

#: minarca_client/main.py:134
msgid "Remote URL (e.g.: https://backup.examples.com): "
msgstr "URL vers le serveur distant (p.e.: http://example.com:8080/) : "

#: minarca_client/main.py:136
msgid "Username: "
msgstr "Nom d'utilisateur : "

#: minarca_client/main.py:138
msgid "Password or access token: "
msgstr "Mot de passe ou jeton d'accès : "

#: minarca_client/main.py:154 minarca_client/main.py:159
msgid "Linked successfully"
msgstr "Lié avec succès"

#: minarca_client/main.py:157
msgid "Do you want to replace the existing repository? (Yes/No): "
msgstr "Souhaitez-vous remplacer le dépôt existant ? (Oui/Non) : "

#: minarca_client/main.py:173
msgid ""
"To update include or exclude patterns, you must configure at least one backup "
"instance."
msgstr ""
"Pour mettre à jour les modèles d'inclusion ou d'exclusion, vous devez configurer "
"au moins une instance de sauvegarde."

#: minarca_client/main.py:241
msgid "From which backup source do you want to restore data from?"
msgstr ""
"A partir de quelle source de sauvegarde voulez-vous restaurer les données ?"

#: minarca_client/main.py:253
msgid "Enter backup instance ID: "
msgstr "Saisir l'identifiant de l'instance de sauvegarde : "

#: minarca_client/main.py:257
#, python-format
msgid "Invalid instance ID: %s"
msgstr "Identifiant d'instance invalide : %s"

#: minarca_client/main.py:261
msgid "Your instance value doesn't match any backup instances"
msgstr "Votre valeur d'instance ne correspond à aucune instance de sauvegarde"

#: minarca_client/main.py:263
msgid "Your instance value matches too many backup instances"
msgstr "Votre valeur d'instance correspond à trop d'instances de sauvegarde"

#: minarca_client/main.py:276
#, python-format
msgid "Do you want to restore %s? (Yes/No): "
msgstr "Voulez-vous restaurer %s (Oui/Non) : "

#: minarca_client/main.py:290
msgid ""
"Are you sure you want to proceed with the restore operation? Please note that "
"this will override your current data. (Yes/No): "
msgstr ""
"Êtes-vous sûr de vouloir procéder à l'opération de restauration ? Veuillez noter "
"que cette opération annulera vos données actuelles. (Oui/Non) : "

#: minarca_client/main.py:356
#, python-format
msgid "Backup Instance: %s"
msgstr "Instance de sauvegarde : %s"

#: minarca_client/main.py:360
#, python-format
msgid "Identifier:             %s"
msgstr "Identifiant:            %s"

#: minarca_client/main.py:362
#, python-format
msgid "Remote server:          %s"
msgstr "Serveur distant :       %s"

#: minarca_client/main.py:364
#, python-format
msgid "Local device:           %s"
msgstr "Destination local :     %s"

#: minarca_client/main.py:365
#, python-format
msgid "Connectivity status:    %s"
msgstr "État de la connectivité : %s"

#: minarca_client/main.py:365
msgid "Connected"
msgstr "Connecté"

#: minarca_client/main.py:365
msgid "Not connected"
msgstr "Non connecté"

#: minarca_client/main.py:368
#, python-format
msgid "Last successful backup: %s"
msgstr "Dernière sauvegarde réussie : %s"

#: minarca_client/main.py:368 minarca_client/main.py:370 minarca_client/main.py:371
#: minarca_client/ui/backup_settings.py:257
msgid "Never"
msgstr "Jamais"

#: minarca_client/main.py:370
#, python-format
msgid "Last backup date:       %s"
msgstr "Date de la dernière sauvegarde : %s"

#: minarca_client/main.py:371
#, python-format
msgid "Last backup status:     %s"
msgstr "État de la dernière sauvegarde : %s"

#: minarca_client/main.py:373
#, python-format
msgid "Details:                %s"
msgstr "Détails:                %s"

#: minarca_client/main.py:375
#, python-format
msgid "Paused until:           %s"
msgstr "En pause jusqu'à :           %s"

#: minarca_client/main.py:393
msgid "Minarca"
msgstr "Minarca"

#: minarca_client/main.py:394
msgid "Application failed to start"
msgstr "L'application ne parvient pas à démarrer"

#: minarca_client/main.py:395
msgid ""
"If the problem persists, check the logs with your administrator or try "
"reinstalling the application."
msgstr ""
"Si le problème persiste, vérifiez les journaux avec votre administrateur ou "
"essayez de réinstaller l'application."

#: minarca_client/main.py:417
msgid ""
"Minarca manages your computer's backup by linking your computer with a "
"centralized server and running backups on a given schedule."
msgstr ""
"Minarca gère la sauvegarde de votre ordinateur en le reliant à un serveur "
"centralisé et en exécutant des sauvegardes selon un calendrier donné."

#: minarca_client/main.py:436
msgid "start a backup in background mode"
msgstr "démarrer une sauvegarde en arrière-plan"

#: minarca_client/main.py:437 minarca_client/main.py:449
msgid "force execution of a backup even if it's not time to run"
msgstr ""
"forcer l'exécution d'une sauvegarde même s'il n'est pas temps de l'exécuter"

#: minarca_client/main.py:441 minarca_client/main.py:453
msgid "Limit backup to the given instance(s)."
msgstr "Limite la sauvegarde à la (aux) instance(s) donnée(s)."

#: minarca_client/main.py:448
msgid "start a backup in foreground mode"
msgstr "démarrer une sauvegarde en mode avant-plan"

#: minarca_client/main.py:460
msgid "exclude files from being backed up"
msgstr "exclure les fichiers à sauvegarder"

#: minarca_client/main.py:464
msgid "Add exclude file pattern to the given instance(s)."
msgstr ""
"Ajoute un modèle de fichier d'exclusion à l'instance ou aux instances données."

#: minarca_client/main.py:468 minarca_client/main.py:481
msgid "file pattern to be excluded. May contain `*` or `?` wildcard"
msgstr ""
"modèle de fichier à exclure. peut contenir un caractère générique `*` ou `?`"

#: minarca_client/main.py:473
msgid "include files to be backed up"
msgstr "inclure les fichiers à sauvegarder"

#: minarca_client/main.py:477
msgid "Add include file pattern to the given instance(s)."
msgstr ""
"Ajoute un modèle de fichier d'inclusion à l'instance (aux instances) donnée(s)."

#: minarca_client/main.py:487
msgid "configure this agent to backup to a new destination (remote or local)"
msgstr ""
"configurer cet agent pour qu'il effectue des sauvegardes vers une nouvelle "
"destination (distante ou locale)"

#: minarca_client/main.py:489
msgid "URL to the remote server. e.g.: http://example.com:8080/"
msgstr "URL du serveur distant, par exemple : http://example.com:8080/"

#: minarca_client/main.py:490
msgid "username to be used for authentication with the remote server"
msgstr ""
"nom d'utilisateur à utiliser pour l'authentification auprès du serveur distant"

#: minarca_client/main.py:494
msgid ""
"password or access token to use for authentication. You will be prompted if not "
"provided"
msgstr ""
"mot de passe ou jeton d'accès à utiliser pour l'authentification. Il serait "
"demandé s'il n'est pas fourni"

#: minarca_client/main.py:496
msgid "repository name to be used"
msgstr "nom du dépôt à utiliser"

#: minarca_client/main.py:500
msgid ""
"replace existing repository on backup destination if it exists without "
"confirmation"
msgstr ""
"remplacer le dépôt existant sur la destination de la sauvegarde s'il existe sans "
"confirmation"

#: minarca_client/main.py:502
msgid "path to local destination"
msgstr "chemin vers la destination locale"

#: minarca_client/main.py:506
msgid "list the include/exclude patterns"
msgstr "liste les modèles d'inclusion/exclusion"

#: minarca_client/main.py:510
msgid "Show include and exclude patterns only for the given instance(s)."
msgstr ""
"Afficher les modèles d'inclusion et d'exclusion uniquement pour la ou les "
"instances données."

#: minarca_client/main.py:517
msgid "restore data from backup"
msgstr "restaurer des données à partir d'une sauvegarde"

#: minarca_client/main.py:521
msgid "Force the use of a given instance for restore."
msgstr "Forcer l'utilisation d'une instance donnée pour la restauration."

#: minarca_client/main.py:527
msgid ""
"Date and time to be restored. Could be 'now' to restore the latest backup. Could "
"be an epoch value like '1682367069'. Could be an ISO date format like "
"'2023-02-24T04:11:09-04:00'. Could be an interval like '3D' for 3 days ago."
msgstr ""
"Date et heure de la restauration. Il peut s'agir de \"now\" pour restaurer la "
"dernière sauvegarde. Il peut s'agir d'une valeur d'époque comme '1682367069'. Il "
"peut s'agir d'un format de date ISO comme '2023-02-24T04:11:09-04:00'. Il peut "
"s'agir d'un intervalle comme \"3D\" pour 3 jours."

#: minarca_client/main.py:533
msgid ""
"Define an alternate location to restore files or folders instead of restoring "
"them in place."
msgstr ""
"Définir un autre emplacement pour restaurer des fichiers ou des dossiers au lieu "
"de les restaurer sur place."

#: minarca_client/main.py:538
msgid "Force execution of restore operation without confirmation from the user."
msgstr ""
"Forcer l'exécution d'une opération de restauration sans confirmation de "
"l'utilisateur."

#: minarca_client/main.py:540
msgid "files and folders to be restored"
msgstr "fichiers et dossiers à restaurer"

#: minarca_client/main.py:544
msgid "stop the backup"
msgstr "arrêter la sauvegarde"

#: minarca_client/main.py:548
msgid "Stop only the given instance(s)."
msgstr "Arrêter uniquement la ou les instances données."

#: minarca_client/main.py:552
msgid "doesn't fail if the backup is not running."
msgstr "n'échoue pas si la sauvegarde n'est pas en cours d'exécution."

#: minarca_client/main.py:557
msgid "create the required scheduled task in Windows Task Scheduler"
msgstr ""
"créer la tâche planifiée requise dans le planificateur de tâches de Windows"

#: minarca_client/main.py:559
msgid "create the required scheduled task in launchd"
msgstr "créer la tâche programmée requise dans launchd"

#: minarca_client/main.py:561
msgid "create the required scheduled task in crontab"
msgstr "créer la tâche programmée requise dans la crontab"

#: minarca_client/main.py:568
msgid "schedule backup to run hourly"
msgstr "planifier la sauvegarde pour qu'elle s'exécute toutes les heures"

#: minarca_client/main.py:575
msgid "schedule backup to run daily"
msgstr "planifier la sauvegarde pour qu'elle s'exécute quotidiennement"

#: minarca_client/main.py:582
msgid "schedule backup to run weekly"
msgstr "planifier la sauvegarde pour qu'elle s'exécute chaque semaine"

#: minarca_client/main.py:587
msgid "Configure only the given instance(s)."
msgstr "Configurer uniquement la ou les instance(s) donnée(s)."

#: minarca_client/main.py:592
msgid "username required to run task when the user is logged out"
msgstr ""
"nom d'utilisateur requis pour exécuter la tâche lorsque l'utilisateur est "
"déconnecté"

#: minarca_client/main.py:593
msgid "password required to run task when the user is logged out"
msgstr ""
"mot de passe requis pour exécuter la tâche lorsque l'utilisateur est déconnecté"

#: minarca_client/main.py:597
msgid "return the current Minarca status"
msgstr "retourner l'état actuel de la minarca"

#: minarca_client/main.py:601
msgid "Show status for the given instance(s)."
msgstr "Affiche l'état de la ou des instances données."

#: minarca_client/main.py:608
msgid "forget backup settings"
msgstr "oublier les paramètres de la sauvegarde"

#: minarca_client/main.py:612
msgid "Forget settings of the given backup instance(s)."
msgstr ""
"Oublie les paramètres de l'instance ou des instances de sauvegarde donnée(s)."

#: minarca_client/main.py:617
msgid "Force forget operation without confirmation from the user."
msgstr ""
"Force l'exécution d'une opération de restauration sans confirmation de "
"l'utilisateur."

#: minarca_client/main.py:624
msgid ""
"temporarily delay the execution of the backup for the given number of hours. "
"Default is 24 hours."
msgstr ""
"retarde temporairement l'exécution de la sauvegarde pendant le nombre d'heures "
"indiqué. La valeur par défaut est de 24 heures."

#: minarca_client/main.py:629
msgid "Pause only the given instance(s)."
msgstr "Mettre en pause uniquement la ou les instances données."

#: minarca_client/main.py:633
msgid "number of hours"
msgstr "nombre d'heures"

#: minarca_client/main.py:638
msgid "clear previously set delay"
msgstr "efface le délai précédemment défini"

#: minarca_client/main.py:647
msgid "verify backup integrity"
msgstr "vérifier l'intégrité de la sauvegarde"

#: minarca_client/main.py:651
msgid "Verify backup integrity of the given backup instance(s)."
msgstr ""
"Vérifier l'intégrité de la sauvegarde de l'instance ou des instances de "
"sauvegarde donnée(s)."

#: minarca_client/main.py:658
msgid "open graphical user interface (default when calling minarcaw)"
msgstr ""
"ouvrir l'interface utilisateur graphique (par défaut avec l'execution de "
"minarcaw)"

#: minarca_client/main.py:664
msgid "For internal use"
msgstr "Pour usage interne"

#: minarca_client/core/exceptions.py:60
#, python-format
msgid "No backup instances match: %s"
msgstr "Aucune instance de sauvegarde ne correspond à : %s"

#: minarca_client/core/exceptions.py:77
#, python-format
msgid "Destination `%s` already exists."
msgstr "La destination `%s` existe déjà."

#: minarca_client/core/exceptions.py:90
msgid "cannot stop process when it's not running."
msgstr ""
"impossible d'arrêter le processus puisqu'il n'est pas en cours d'exécution."

#: minarca_client/core/exceptions.py:150
#, python-format
msgid "process terminated with an exception. Check logs for more details: %s"
msgstr ""
"le processus de sauvegarde s'est terminé avec une exception, vérifiez les "
"journaux pour plus de détails : %s"

#: minarca_client/core/exceptions.py:165
#, python-format
msgid "process returned a non-zero exit status (%s). Check logs for more details"
msgstr ""
"le processus de sauvegarde a renvoyé un état de sortie non nul (%s), consultez "
"les journaux pour plus de détails"

#: minarca_client/core/exceptions.py:183
msgid "cannot start process when it's already running."
msgstr ""
"impossible de démarrer le processus puisqu'il est déjà en cours d'exécution."

#: minarca_client/core/exceptions.py:195
msgid "backup not yet scheduled to run. You may force execution using `--force`"
msgstr ""
"sauvegarde n'est pas encore planifiée pour s'exécuter, vous pouvez forcer "
"l'exécution en utilisant `--force`"

#: minarca_client/core/exceptions.py:211
msgid ""
"Unable to connect to the remote server. The problem may be with the remote "
"server. If the problem persists, contact your system administrator to check the "
"SSH server configuration and a possible firewall blocking the connection."
msgstr ""
"Impossible de se connecter au serveur distant. Le problème peut provenir du "
"serveur distant. Si le problème persiste, contactez votre administrateur système "
"pour vérifier la configuration du serveur SSH et un éventuel pare-feu bloquant "
"la connexion."

#: minarca_client/core/exceptions.py:234
msgid ""
"The connection to the remote server failed because our identity was refused. The "
"problem may lie with the remote server. If the problem persists, contact your "
"system administrator to check your SSH identity."
msgstr ""
"La sauvegarde a échoué parce que votre identité a été refusée par le serveur "
"distant. Le problème peut provenir du serveur distant. Si le problème persiste, "
"contactez votre administrateur système pour vérifier votre identité SSH."

#: minarca_client/core/exceptions.py:252
msgid ""
"The connection to the remote server cannot be established securely because the "
"server's identity has changed. If the problem persists, contact your system "
"administrator to verify the server's identity."
msgstr ""
"La sauvegarde a échoué en raison de l'identité inconnue du serveur distant. Si "
"le problème persiste, contactez votre administrateur système pour vérifier "
"l'identité du serveur."

#: minarca_client/core/exceptions.py:268
msgid ""
"Backup failed due to disk quota exceeded. Please free up disk space to ensure "
"successful backup."
msgstr ""
"La sauvegarde a échoué en raison d'un dépassement du quota de disque. Veuillez "
"libérer de l'espace disque pour assurer la réussite de la sauvegarde."

#: minarca_client/core/exceptions.py:280
msgid ""
"Backup failed due to disk being full. Please clear space on the disk to proceed "
"with the backup."
msgstr ""
"La sauvegarde a échoué car le disque est plein. Veuillez libérer de l'espace sur "
"le disque pour poursuivre la sauvegarde."

#: minarca_client/core/exceptions.py:293
msgid ""
"The connection to the remote server has failed due to an unresolvable host name. "
"Please check your network connection and ensure that the host name is still "
"valid. If the problem persists, contact your system administrator to check the "
"host name."
msgstr ""
"La connexion au serveur distant a échoué en raison d'un nom d'hôte non "
"résoluble. Veuillez vérifier votre connexion réseau et vous assurer que le nom "
"d'hôte est toujours valide. Si le problème persiste, contactez votre "
"administrateur système pour vérifier le nom d'hôte."

#: minarca_client/core/exceptions.py:310
msgid ""
"The connection to the remote server has failed due to an unsupported version of "
"the Minarca agent on the remote server. Consider updating your agent or server."
msgstr ""
"La sauvegarde a échoué en raison d'une version non prise en charge de l'agent "
"Minarca sur le serveur distant. Pensez à mettre à jour votre agent ou votre "
"serveur."

#: minarca_client/core/exceptions.py:324
msgid "The path you are trying to restore from backup does not exist."
msgstr "Le chemin que vous essayez de restaurer depuis la sauvegarde n'existe pas."

#: minarca_client/core/exceptions.py:337
msgid "Another backup session is currently in progress on the remote server."
msgstr "Une autre session de sauvegarde est en cours sur le serveur distant."

#: minarca_client/core/exceptions.py:350
msgid ""
"An internal error was raised by an unknown operation sent to the background "
"process."
msgstr ""
"Une erreur interne a été soulevée par une opération inconnue envoyée au "
"processus d'arrière-plan."

#: minarca_client/core/exceptions.py:363
msgid ""
"Backup Destination Not Found. Please ensure that your external disk or network "
"share is properly connected and accessible."
msgstr ""
"Destination de la sauvegarde introuvable. Veuillez vous assurer que votre disque "
"externe ou votre partage de réseau est correctement connecté et accessible."

#: minarca_client/core/exceptions.py:370
msgid ""
"Backup unsuccessful due to a copy operation encountering an issue, potentially "
"because the device is disconnected. Ensure your device is properly connected."
msgstr ""
"Échec de la sauvegarde en raison d'un problème rencontré lors d'une opération de "
"copie, peut-être parce que l'appareil est déconnecté. Assurez-vous que votre "
"appareil est correctement connecté."

#: minarca_client/core/exceptions.py:385
msgid "Repository cannot be found on remote server"
msgstr "Le dépôt est introuvable sur le serveur distant"

#: minarca_client/core/exceptions.py:391
#, python-format
msgid "Repository `%s` cannot be found on remote server"
msgstr "Le dépôt `%s` est introuvable sur le serveur distant"

#: minarca_client/core/exceptions.py:415
msgid ""
"The connection was terminated unexpectedly, which may indicate an issue with the "
"remote server. If the problem persists, contact your system administrator to "
"review the server logs and diagnose the cause."
msgstr ""
"La connexion a été interrompue de manière inattendue, ce qui peut indiquer un "
"problème avec le serveur distant. Si le problème persiste, contactez votre "
"administrateur système pour consulter les journaux du serveur et diagnostiquer "
"la cause du problème."

#: minarca_client/core/exceptions.py:432
#, python-format
msgid ""
"your file specification [%s] doesn't match any of the base directories of your "
"system"
msgstr ""
"votre spécification de fichier [%s] ne correspond à aucun des répertoires de "
"base de votre système"

#: minarca_client/core/exceptions.py:453
msgid "No files included in backup. Check configuration."
msgstr "Aucun fichier n'est inclus dans la sauvegarde. Vérifier la configuration."

#: minarca_client/core/exceptions.py:467
msgid "not configured, use `minarca configure` to configure remote host"
msgstr "non configuré, utilisez `minarca configure` pour configurer l'hôte distant"

#: minarca_client/core/exceptions.py:480
msgid "Cannot establish connection to remote server."
msgstr "Échec de l'établissement de la connectivité avec le serveur distant."

#: minarca_client/core/exceptions.py:481
#, python-format
msgid ""
"Your computer cannot establish a connection to the remote server. Make sure your "
"Internet connection is working and that the following URL is accessible with a "
"Web browser: %s"
msgstr ""
"Votre ordinateur ne parvient pas à établir une connexion avec le serveur "
"distant. Assurez-vous que votre connexion Internet fonctionne et que l'URL "
"suivante est accessible avec un navigateur Web : %s"

#: minarca_client/core/exceptions.py:497
#, python-format
msgid "Invalid remote server URL: %s"
msgstr "L'URL du serveur distant n'est pas valide : %s"

#: minarca_client/core/exceptions.py:498
msgid ""
"The remote server URL you entered for the connection is not valid. Check that "
"you have entered the correct value. The URL must begin with `http://` or "
"`https://` followed by a domain name."
msgstr ""
"L'URL du serveur distant que vous avez saisi pour la connexion n'est pas valide. "
"Vérifiez que vous avez saisi la bonne valeur. L'URL doit commencer par `http://` "
"ou `https://` suivi d'un nom de domaine."

#: minarca_client/core/exceptions.py:515
msgid "Invalid username or password"
msgstr "Nom d'utilisateur ou mot de passe invalide"

#: minarca_client/core/exceptions.py:516
msgid ""
"The username or password you entered to connect to the remote server is not "
"valid. If you have enabled multi-factor authentication, you need to use an "
"access token."
msgstr ""
"Le nom d'utilisateur ou le mot de passe que vous avez saisi pour vous connecter "
"au serveur distant n'est pas valide. Si vous avez activé l'authentification "
"multifactorielle, vous devez utiliser un jeton d'accès."

#: minarca_client/core/exceptions.py:533
msgid "The remote server returned an error. You may try again later."
msgstr "Le serveur distant a renvoyé une erreur. Vous pouvez réessayer plus tard."

#: minarca_client/core/exceptions.py:545
msgid "Backup Destination Occupied"
msgstr "Destination de sauvegarde occupée"

#: minarca_client/core/exceptions.py:546
msgid ""
"Unable to proceed with the selected destination as it contains existing data. If "
"you intend to use this location, kindly empty the directory of any files and "
"folders."
msgstr ""
"Impossible d'utiliser la destination sélectionnée car elle contient des données "
"existantes. Si vous avez l'intention d'utiliser cet emplacement, veuillez vider "
"le répertoire de tous les fichiers et dossiers."

#: minarca_client/core/exceptions.py:557
msgid "Destination Not Suitable"
msgstr "Destination inadaptée"

#: minarca_client/core/exceptions.py:558
msgid ""
"Unable to proceed with the selected destination as it cannot be initialized. "
"Make sure the external device is connected and operational."
msgstr ""
"Impossible de poursuivre avec la destination sélectionnée car elle ne peut pas "
"être initialisée. Assurez-vous que l'appareil externe est connecté et "
"opérationnel."

#: minarca_client/core/exceptions.py:569
msgid ""
"Repository name must contain only letters, numbers, dashes (-), and dots (.)"
msgstr ""
"Le nom du dépôt ne doit contenir que des lettres, des chiffres, des tirets (-) "
"et des points (.)."

#: minarca_client/core/exceptions.py:583
msgid ""
"These settings conflict with an existing backup and therefore cannot be created."
msgstr ""
"Ces paramètres entrent en conflit avec une sauvegarde existante et ne peuvent "
"donc pas être créés."

#: minarca_client/core/exceptions.py:584
msgid ""
"It is not possible to create two backups with the same destination settings. "
"These will conflict during backup. Be sure to define a different destination for "
"this backup."
msgstr ""
"Il n'est pas possible de créer deux sauvegardes avec les mêmes paramètres de "
"destination. Ceux-ci entreront en conflit lors de la sauvegarde. Veillez à "
"définir une destination différente pour cette sauvegarde."

#: minarca_client/core/exceptions.py:605
msgid ""
"The remote server could not create the necessary security context, which may "
"indicate an issue with the server. If the problem persists, please contact your "
"system administrator to review the server logs and diagnose the cause."
msgstr ""
"Le serveur distant n'a pas pu créer le contexte de sécurité nécessaire, ce qui "
"peut indiquer un problème avec le serveur. Si le problème persiste, veuillez "
"contacter votre administrateur système pour qu'il examine les journaux du "
"serveur et en diagnostique la cause."

#: minarca_client/core/latest.py:31
msgid "https://minarca.org/download/"
msgstr "https://minarca.org/download/"

#: minarca_client/core/pattern.py:87
msgid "User's Documents"
msgstr "Documents de l'utilisateur"

#: minarca_client/core/pattern.py:89
msgid "Minarca Config"
msgstr "Configuration Minarca"

#: minarca_client/core/pattern.py:96 minarca_client/core/pattern.py:155
#: minarca_client/core/pattern.py:176
msgid "Firefox Bookmark"
msgstr "Favoris Firefox"

#: minarca_client/core/pattern.py:103 minarca_client/core/pattern.py:162
#: minarca_client/core/pattern.py:177
msgid "Chrome Bookmark"
msgstr "Favoris Chrome"

#: minarca_client/core/pattern.py:110
msgid "Outlook Offline Data"
msgstr "Données Outlook hors ligne"

#: minarca_client/core/pattern.py:117
msgid "Outlook Address Books"
msgstr "Carnets d'adresses Outlook"

#: minarca_client/core/pattern.py:122
msgid "Thumbnails cache"
msgstr "Cache de vignettes"

#: minarca_client/core/pattern.py:123
msgid "Arrangement of a Windows folder"
msgstr "Agencement d'un dossier Windows"

#: minarca_client/core/pattern.py:124
msgid "Swap System File"
msgstr "Fichier d'échange (Mémoire Virtuelle)"

#: minarca_client/core/pattern.py:125
msgid "Page System File"
msgstr "Fichier de pagination"

#: minarca_client/core/pattern.py:126
msgid "Hibernation System File"
msgstr "Fichier d'hibernation"

#: minarca_client/core/pattern.py:127
msgid "System Volume Information"
msgstr "System Volume Information"

#: minarca_client/core/pattern.py:128
msgid "System Recovery"
msgstr "Récupération système"

#: minarca_client/core/pattern.py:129
msgid "Recycle bin"
msgstr "Corbeille"

#: minarca_client/core/pattern.py:130 minarca_client/core/pattern.py:183
msgid "Temporary Folder"
msgstr "Dossier temporaire"

#: minarca_client/core/pattern.py:131
msgid "AutoCAD backup files"
msgstr "Fichiers de sauvegarde AutoCAD"

#: minarca_client/core/pattern.py:132
msgid "Office temporary files"
msgstr "Fichiers temporaires Office"

#: minarca_client/core/pattern.py:133
msgid "Outlook IMAP temporary files"
msgstr "Fichiers temporaires d'Outlook IMAP"

#: minarca_client/core/pattern.py:134
msgid "Outlook POP temporary files"
msgstr "Fichiers temporaires d'Outlook POP"

#: minarca_client/core/pattern.py:135
msgid "Dynacom Backup file"
msgstr "Fichier de sauvegarde Dynacom"

#: minarca_client/core/pattern.py:136
msgid "Google Drive temporary upload files"
msgstr "Fichiers de temporaire de Google Drive"

#: minarca_client/core/pattern.py:137
msgid "Google Drive temporary download files"
msgstr "Fichiers de téléchargement temporaire de Google Drive"

#: minarca_client/core/pattern.py:142 minarca_client/core/pattern.py:171
msgid "OneDrive GUID File"
msgstr "Fichier GUID OneDrive"

#: minarca_client/core/pattern.py:145
msgid "Google Drive Shortcut Metadata"
msgstr "Métadonnées des raccourcis Google Drive"

#: minarca_client/core/pattern.py:146
msgid "Google Drive Revision History"
msgstr "Historique des révisions de Google Drive"

#: minarca_client/core/pattern.py:147
msgid "Google Drive Encrypted"
msgstr "Google Drive crypté"

#: minarca_client/core/pattern.py:167
msgid "Desktop Services Store"
msgstr "Desktop Services Store"

#: minarca_client/core/pattern.py:180
msgid "dev filesystem"
msgstr "système de fichiers /dev"

#: minarca_client/core/pattern.py:181
msgid "proc filesystem"
msgstr "système de fichiers /proc"

#: minarca_client/core/pattern.py:182
msgid "sys filesystem"
msgstr "système de fichiers /sys"

#: minarca_client/core/pattern.py:184
msgid "Volatile program files"
msgstr "Fichiers volatile /run"

#: minarca_client/core/pattern.py:185
msgid "Mounted filesystems"
msgstr "Systèmes de fichiers montés /mnt"

#: minarca_client/core/pattern.py:186
msgid "External media"
msgstr "Médias externes /media"

#: minarca_client/core/pattern.py:187
msgid "Ext4 Lost and Found"
msgstr "Ext4 perdu et trouvé"

#: minarca_client/core/pattern.py:188
msgid "Hidden temporary files"
msgstr "Fichiers temporaires cachés"

#: minarca_client/core/pattern.py:189
msgid "Vim temporary files"
msgstr "Fichiers temporaires Vim"

#: minarca_client/core/scheduler.py:23
msgid "Minarca Backup"
msgstr "Sauvegarde Minarca"

#: minarca_client/core/scheduler.py:76
msgid ""
"Keeps your Minarca Backup Software running. If this task is disabled or stopped, "
"your Minarca backup will stop working. This task gets created when linking "
"Minarca with a central backup server. When installing Minarca on a Windows "
"Server, it's preferable to change the settings of this task and select 'Run "
"whether user is logged on or not' to make sure the backup is running even when "
"nobody is using the server."
msgstr ""
"Maintient le fonctionnement de votre logiciel de sauvegarde Minarca. Si cette "
"tâche est désactivée ou arrêté, votre sauvegarde Minarca cessera de fonctionner. "
"Cette tâche est créée lors de la liaison de Minarca avec un serveur de "
"sauvegarde central. Lors de l'installation Minarca sur un serveur Windows, il "
"est préférable de modifier les paramètres de cette tâche et sélectionnez « "
"Exécuter que l'utilisateur soit connecté ou non » pour vous assurer la "
"sauvegarde s'exécute même lorsque personne n'utilise le serveur."

#: minarca_client/core/scheduler.py:106
msgid ""
"A problem prevents the scheduling of backup jobs. Try running the application "
"with Administrator rights."
msgstr ""
"Un problème empêche la planification des tâches de sauvegarde. Essayez "
"d'exécuter l'application avec des droits d'administrateur."

#: minarca_client/core/scheduler.py:113
msgid ""
"The user account is unknown or the password is incorrect. Be sure to enter your "
"Windows credentials."
msgstr ""
"Le compte utilisateur est inconnu ou le mot de passe est incorrect. Veillez à "
"saisir vos informations d'identification Windows."

#: minarca_client/core/status.py:152
msgid "Your backup is outdated"
msgstr "Votre sauvegarde est obsolète"

#: minarca_client/core/status.py:153
#, python-format
msgid ""
"Your backup %s is outdated by over %s days. Please plug in your local device and "
"run the backup."
msgstr ""
"Votre sauvegarde %s est périmée de plus de %s jours. Veuillez brancher votre "
"appareil local et exécuter la sauvegarde."

#: minarca_client/core/notification/_notification_win.py:127
msgid "Show details"
msgstr "Afficher les détails"

#: minarca_client/dialogs/_dialogs_cocoa.py:57
msgid "Yes"
msgstr "Oui"

#: minarca_client/dialogs/_dialogs_cocoa.py:57
msgid "No"
msgstr "Non"

#: minarca_client/ui/about_menu.py:20
#: minarca_client/ui/backup_connection_local.py:30
msgid "Browse"
msgstr "Parcourir"

#: minarca_client/ui/about_menu.py:20
msgid "Settings"
msgstr "Réglages"

#: minarca_client/ui/about_menu.py:20
msgid "Get Help"
msgstr "Obtenir de l'aide"

#: minarca_client/ui/about_menu.py:20
msgid "Help"
msgstr "Aide"

#: minarca_client/ui/about_menu.py:20
msgid "Website"
msgstr "Site web"

#: minarca_client/ui/about_menu.py:20
msgid "Minarca Agent"
msgstr "Agent Minarca"

#: minarca_client/ui/about_menu.py:20
#, python-format
msgid "Version %s"
msgstr "Version %s"

#: minarca_client/ui/about_menu.py:20
msgid "Update now"
msgstr "Mettre à jour maintenant"

#: minarca_client/ui/about_menu.py:20
msgid "Copyright © 2025 IKUS Software"
msgstr "Copyright © 2025 IKUS Software"

#: minarca_client/ui/about_menu.py:128 minarca_client/ui/about_menu.py:130
#: minarca_client/ui/backup_connection_local.py:262
#, python-format
msgid "%s on %s"
msgstr "%s sur %s"

#: minarca_client/ui/about_menu.py:228
msgid "Checking for updates..."
msgstr "Recherche de mises à jour..."

#: minarca_client/ui/about_menu.py:230
msgid "Unable to verify update availability at this time."
msgstr "Impossible de vérifier la disponibilité de la mise à jour actuellement."

#: minarca_client/ui/about_menu.py:232
#, python-format
msgid "New version %s available"
msgstr "Nouvelle version %s disponible"

#: minarca_client/ui/about_menu.py:234
msgid "Current version is up-to-date"
msgstr "Version actuelle à jour"

#: minarca_client/ui/backup_advance.py:19
msgid "Configure your advanced backup settings to fine-tune your preferences."
msgstr ""
"Configurez vos paramètres de sauvegarde avancés pour affiner vos préférences."

#: minarca_client/ui/backup_advance.py:19
msgid "Script hooks"
msgstr "Commandes"

#: minarca_client/ui/backup_advance.py:19
msgid ""
"Set up custom scripts to run before or after backups by defining the command "
"line to be executed."
msgstr ""
"Configurez des scripts personnalisés à exécuter avant ou après les sauvegardes "
"en définissant la ligne de commande à exécuter."

#: minarca_client/ui/backup_advance.py:19
msgid "Pre-backup command"
msgstr "Commande pré-sauvegarde"

#: minarca_client/ui/backup_advance.py:19
msgid "Post-backup command"
msgstr "Commande post-sauvegarde"

#: minarca_client/ui/backup_advance.py:19
msgid "Continue the backup if one of the command fails"
msgstr "Poursuivre la sauvegarde si l'une des commandes échoue"

#: minarca_client/ui/backup_advance.py:19
#: minarca_client/ui/backup_connection_local.py:30
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_patterns.py:23 minarca_client/ui/backup_settings.py:26
msgid "Cancel"
msgstr "Annuler"

#: minarca_client/ui/backup_advance.py:19
#: minarca_client/ui/backup_connection_local.py:30
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_patterns.py:23 minarca_client/ui/backup_settings.py:26
msgid "Save"
msgstr "Sauvegarder"

#: minarca_client/ui/backup_advance.py:127 minarca_client/ui/backup_settings.py:350
msgid "Please wait. Saving settings..."
msgstr "Veuillez patienter. Enregistrement des paramètres..."

#: minarca_client/ui/backup_advance.py:144
msgid "Cannot save advance settings"
msgstr "Impossible d'enregistrer les paramètres avancés"

#: minarca_client/ui/backup_advance.py:145
msgid ""
"An unknown problem encountered while trying to save the advance backup settings. "
"If the problem persist contact your administrator."
msgstr ""
"Un problème inconnu a été rencontré lors de l'enregistrement des paramètres de "
"la sauvegarde avancée. Si le problème persiste, contactez votre administrateur."

#: minarca_client/ui/backup_card.py:21 minarca_client/ui/backup_create.py:11
#: minarca_client/ui/side_pannel.py:102
msgid "Online backup"
msgstr "Sauvegarde en ligne"

#: minarca_client/ui/backup_card.py:21 minarca_client/ui/backup_create.py:11
#: minarca_client/ui/side_pannel.py:109
msgid "Local backup"
msgstr "Sauvegarde locale"

#: minarca_client/ui/backup_card.py:21
msgid "Paused"
msgstr "En pause"

#: minarca_client/ui/backup_card.py:21
msgid "Active"
msgstr "Actif"

#: minarca_client/ui/backup_card.py:21 minarca_client/ui/backup_settings.py:26
msgid "Backup configuration"
msgstr "Configuration de la sauvegarde"

#: minarca_client/ui/backup_card.py:21 minarca_client/ui/backup_restore_files.py:28
msgid "File selection"
msgstr "Sélection de fichiers"

#: minarca_client/ui/backup_card.py:21
msgid "Advance settings"
msgstr "Paramètres avancés"

#: minarca_client/ui/backup_card.py:21
msgid "Restore backup"
msgstr "Restaurer une sauvegarde"

#: minarca_client/ui/backup_card.py:293
msgid "Calculating disk usage"
msgstr "Calcul de l'utilisation du disque"

#: minarca_client/ui/backup_card.py:295
msgid "Cannot determine disk usage"
msgstr "Impossible de déterminer l'utilisation du disque"

#: minarca_client/ui/backup_card.py:296
#, python-format
msgid "Used space %s"
msgstr "Espace utilisé %s"

#: minarca_client/ui/backup_card.py:304
#, python-format
msgid "Total space %s"
msgstr "Espace total %s"

#: minarca_client/ui/backup_card.py:309
msgid "Stopping..."
msgstr "Arrêt..."

#: minarca_client/ui/backup_card.py:309
msgid "Starting..."
msgstr "Démarage..."

#: minarca_client/ui/backup_card.py:314
msgid "Stop Restore"
msgstr "Arrêter la restauration"

#: minarca_client/ui/backup_card.py:315
msgid "Stop Backup"
msgstr "Arrêter la sauvegarde"

#: minarca_client/ui/backup_card.py:317
msgid "Start Backup now"
msgstr "Démarrer la sauvegarde"

#: minarca_client/ui/backup_card.py:325 minarca_client/ui/backup_logs.py:286
msgid "No backup yet"
msgstr "Pas encore de sauvegarde"

#: minarca_client/ui/backup_card.py:329
msgid "Backup in progress..."
msgstr "Sauvegarde en cours..."

#: minarca_client/ui/backup_card.py:330 minarca_client/ui/backup_logs.py:290
#, python-format
msgid "Last backup: %s"
msgstr "Dernière sauvegarde : %s"

#: minarca_client/ui/backup_card.py:333
msgid "Restore in progress..."
msgstr "Restauration en cours..."

#: minarca_client/ui/backup_card.py:334 minarca_client/ui/backup_logs.py:292
#, python-format
msgid "Last restore: %s"
msgstr "Dernière restauration : %s"

#: minarca_client/ui/backup_card.py:341
#: minarca_client/ui/backup_connection_remote.py:21
msgid "Server connection"
msgstr "Connexion au serveur"

#: minarca_client/ui/backup_card.py:341
msgid "Local connection"
msgstr "Connexion locale"

#: minarca_client/ui/backup_card.py:385
msgid "Pause Backup Job Confirmation"
msgstr "Confirmation de la mise en pause de la sauvegarde"

#: minarca_client/ui/backup_card.py:386
msgid "Are you sure you want to pause the backup job?"
msgstr "Êtes-vous sûr de vouloir mettre en pause la tâche de sauvegarde ?"

#: minarca_client/ui/backup_card.py:387
msgid ""
"Pausing the backup job will temporarily suspend the ongoing backup process for "
"the next 24 hours. This action may affect the availability of recent data "
"restore points and introduce delays in the backup schedule. Please confirm your "
"intention before proceeding."
msgstr ""
"La mise en pause de la tâche de sauvegarde suspend temporairement le processus "
"de sauvegarde en cours pour les 24 heures à venir. Cette action peut affecter la "
"disponibilité des points de restauration des données récentes et entraîner des "
"retards dans le calendrier de sauvegarde. Veuillez confirmer votre intention "
"avant de poursuivre."

#: minarca_client/ui/backup_card.py:406
msgid "Start Backup"
msgstr "Démarrer la sauvegarde"

#: minarca_client/ui/backup_card.py:407
msgid "A problem occurred when trying to start the backup process."
msgstr "Un problème s'est produit lors du lancement du processus de sauvegarde."

#: minarca_client/ui/backup_card.py:408
msgid ""
"This usually indicate a problem with the installation. Try re-installing Minarca "
"Backup."
msgstr ""
"Cela indique généralement un problème d'installation. Essayez de réinstaller "
"Minarca Backup."

#: minarca_client/ui/backup_card.py:422 minarca_client/ui/backup_logs.py:346
msgid "Stop process"
msgstr "Arrêt du processus"

#: minarca_client/ui/backup_card.py:423 minarca_client/ui/backup_logs.py:347
msgid "A problem occurred when trying to stop the process."
msgstr "Un problème est survenu lors de l'arrêt du processus."

#: minarca_client/ui/backup_connection_local.py:30
msgid "Select a location to be used for backing up your data."
msgstr "Sélectionnez l'emplacement à utiliser pour la sauvegarde de vos données."

#: minarca_client/ui/backup_connection_local.py:30
msgid "Target location"
msgstr "Emplacement cible"

#: minarca_client/ui/backup_connection_local.py:30
msgid "Edit target location"
msgstr "Modifier l'emplacement cible"

#: minarca_client/ui/backup_connection_local.py:30
#: minarca_client/ui/backup_connection_remote.py:21
msgid "Backup name"
msgstr "Nom de la sauvegarde"

#: minarca_client/ui/backup_connection_local.py:30
msgid "Refresh"
msgstr "Rafraîchir"

#: minarca_client/ui/backup_connection_local.py:30
msgid ""
"No external drive has been detected for data backup. Plug in your external drive "
"and click on the refresh button to update this list. If your device is not on "
"the list, check its connectivity and make sure it's switched on."
msgstr ""
"Aucun lecteur externe n'a été détecté pour la sauvegarde des données. Branchez "
"votre disque externe et cliquez sur le bouton d'actualisation pour mettre à jour "
"cette liste. Si votre appareil ne figure pas dans la liste, vérifiez sa "
"connectivité et assurez-vous qu'il est allumé."

#: minarca_client/ui/backup_connection_local.py:30
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_create.py:11 minarca_client/ui/backup_logs.py:26
#: minarca_client/ui/backup_restore_date.py:25
#: minarca_client/ui/backup_restore_files.py:28
#: minarca_client/ui/backup_settings.py:26
msgid "Back"
msgstr "Retour"

#: minarca_client/ui/backup_connection_local.py:30
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_patterns.py:23
#: minarca_client/ui/backup_restore_date.py:25
#: minarca_client/ui/backup_settings.py:26
msgid "Next"
msgstr "Suivant"

#: minarca_client/ui/backup_connection_local.py:30
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_settings.py:26
msgid "Delete backup settings"
msgstr "Effacer les paramètres de sauvegarde"

#: minarca_client/ui/backup_connection_local.py:275
#, python-format
msgid "%s Drive with %s available space"
msgstr "Lecteur %s avec %s d'espace disponible"

#: minarca_client/ui/backup_connection_local.py:277
#, python-format
msgid " • Format %s"
msgstr " • Format %s"

#: minarca_client/ui/backup_connection_local.py:286
msgid ""
"Detected as a fixed device. Prefer using removable or network storage to avoid "
"data loss."
msgstr ""
"Détecté comme un appareil fixe. Préférez l'utilisation d'un support de stockage "
"amovible ou en réseau pour éviter toute perte de données."

#: minarca_client/ui/backup_connection_local.py:288
msgid ""
"Ensure this network location is configured to automatically reconnect to avoid "
"data loss."
msgstr ""
"Assurez-vous que cet emplacement réseau est configuré pour se reconnecter "
"automatiquement afin d'éviter toute perte de données."

#: minarca_client/ui/backup_connection_local.py:290
msgid "FAT32 file system is not recommended for backup."
msgstr "Le système de fichiers FAT32 n'est pas recommandé pour la sauvegarde."

#: minarca_client/ui/backup_connection_local.py:292
msgid "Samba share over Gnome Virtual File system is not compatible."
msgstr ""
"Le partage de Samba sur le système de fichiers virtuels de Gnome n'est pas "
"compatible."

#: minarca_client/ui/backup_connection_local.py:294
msgid ""
"NTFS isn't recommended on Linux due to remount issues after improper unmounting."
msgstr ""
"NTFS n'est pas recommandé sous Linux en raison de problèmes de remontage après "
"un démontage incorrect."

#: minarca_client/ui/backup_connection_local.py:297
msgid "Available disk space at this location is limited."
msgstr "L'espace disque disponible à cet endroit est limité."

#: minarca_client/ui/backup_connection_local.py:425
msgid "You don't have permissions to write at this location."
msgstr "Vous n'avez pas le droit d'écrire à cet endroit."

#: minarca_client/ui/backup_connection_local.py:431
msgid "Destination already exists"
msgstr "La destination existe déjà"

#: minarca_client/ui/backup_connection_local.py:432
#: minarca_client/ui/backup_connection_remote.py:286
msgid "Do you want to replace the existing repository?"
msgstr "Vous souhaitez remplacer le dépôt existant ?"

#: minarca_client/ui/backup_connection_local.py:433
msgid ""
"The selected destination already exists at this location. If you continue with "
"this repository, you will replace its content using this computer. "
msgstr ""
"La destination sélectionnée existe déjà à cet endroit. Si vous continuez avec ce "
"dépôt, vous remplacerez son contenu en utilisant cet ordinateur. "

#: minarca_client/ui/backup_connection_local.py:447
msgid "Unknown problem occurred when trying to configure the destination."
msgstr "Un problème inconnu survient lors de la configuration de la destination."

#: minarca_client/ui/backup_connection_local.py:477
msgid "Please wait. Scanning for removable disks..."
msgstr "Veuillez patienter. Recherche d'un disque amovible..."

#: minarca_client/ui/backup_connection_local.py:488
msgid ""
"Please choose an external device or network share as your backup destination."
msgstr ""
"Veuillez choisir un périphérique externe ou un partage de réseau comme "
"destination de la sauvegarde."

#: minarca_client/ui/backup_connection_local.py:499
#: minarca_client/ui/backup_connection_local.py:500
msgid "Unable to retrieve information from selected location"
msgstr ""
"Impossible de récupérer des informations à partir de l'emplacement sélectionné"

#: minarca_client/ui/backup_connection_local.py:501
msgid ""
"Unable to obtain detailed information on the selected location. Please ensure "
"that this location is accessible and valid. If the problem persists, consult the "
"application log with your administrator."
msgstr ""
"Impossible d'obtenir des informations détaillées sur le lieu sélectionné. "
"Veuillez vous assurer que cet emplacement est accessible et valide. Si le "
"problème persiste, consultez le journal de l'application avec votre "
"administrateur."

#: minarca_client/ui/backup_connection_local.py:525
msgid "Please wait. Initializing backup..."
msgstr "Veuillez patienter. Initialisation de la sauvegarde..."

#: minarca_client/ui/backup_connection_local.py:537
#: minarca_client/ui/backup_connection_remote.py:253
#: minarca_client/ui/backup_settings.py:428
msgid "Are you sure?"
msgstr "Êtes-vous sûr ?"

#: minarca_client/ui/backup_connection_local.py:538
msgid "Are you sure you want to delete this backup configuration?"
msgstr "Êtes-vous sûr de vouloir supprimer cette configuration de sauvegarde ?"

#: minarca_client/ui/backup_connection_local.py:539
msgid ""
"If you delete this backup configuration, this Minarca agent will erase its "
"identity and will no longer run backup on schedule."
msgstr ""
"Si vous supprimez cette configuration de sauvegarde, l'agent Minarca perdra son "
"identité et n'exécutera plus de sauvegarde selon le calendrier prévu."

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Provide your login details to configure remote backup."
msgstr ""
"Indiquez vos données de connexion pour configurer la sauvegarde à distance."

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Edit server connection"
msgstr "Modifier la connexion au serveur"

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Address (IP or domain)"
msgstr "Adresse (IP ou domaine)"

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Username"
msgstr "Nom d'utilisateur"

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Password"
msgstr "Mot de passe"

#: minarca_client/ui/backup_connection_remote.py:243
msgid "Please wait. Initializing backup on remote server..."
msgstr ""
"Veuillez patienter. Initialisation de la sauvegarde sur le serveur distant..."

#: minarca_client/ui/backup_connection_remote.py:254
#: minarca_client/ui/backup_settings.py:429
msgid "Are you sure you want to forget these backup settings?"
msgstr "Êtes-vous sûr de vouloir oublier ces paramètres de sauvegarde ?"

#: minarca_client/ui/backup_connection_remote.py:255
#: minarca_client/ui/backup_settings.py:430
msgid "If you forget these settings, the backup will no longer run on schedule."
msgstr ""
"Si vous oubliez ces paramètres, la sauvegarde ne s'exécutera plus selon le "
"calendrier prévu."

#: minarca_client/ui/backup_connection_remote.py:285
msgid "Repository name already exists"
msgstr "Le nom du dépôt existe déjà"

#: minarca_client/ui/backup_connection_remote.py:287
msgid ""
"The repository name you have entered already exists on the remote server. If you "
"continue with this repository, you will replace its content using this computer. "
"Otherwise, you must enter a different repository name."
msgstr ""
"Le nom de dépôt que vous avez entré existe déjà sur le serveur distant. Si vous "
"continuez avec ce nom, vous remplacerez son contenu avec celui de cet "
"ordinateur. Sinon, vous devez entrer un autre nom de dépôt."

#: minarca_client/ui/backup_connection_remote.py:302
msgid "Failed to establish connectivity with remote server."
msgstr "Échec de l'établissement de la connectivité avec le serveur distant."

#: minarca_client/ui/backup_connection_remote.py:306
msgid "Unknown problem occured when connecting to the remote server."
msgstr "Un problème inconnu s'est produit lors de la connexion au serveur distant."

#: minarca_client/ui/backup_connection_remote.py:307
#, python-format
msgid ""
"An error occurred during the connection to Minarca server.\n"
"\n"
"Details: %s"
msgstr ""
"Une erreur s'est produite lors de la connexion au serveur Minarca.\n"
"\n"
"Détails : %s"

#: minarca_client/ui/backup_create.py:11
msgid "Create a backup"
msgstr "Créer une sauvegarde"

#: minarca_client/ui/backup_create.py:11
msgid "Dedicated centralized server"
msgstr "Serveur central dédié"

#: minarca_client/ui/backup_create.py:11
msgid "Accessible anywhere"
msgstr "Accessible partout"

#: minarca_client/ui/backup_create.py:11
msgid "Remote backup"
msgstr "Sauvegarde à distance"

#: minarca_client/ui/backup_create.py:11
msgid "Setup"
msgstr "Configurer"

#: minarca_client/ui/backup_create.py:11
msgid "External disk or network share"
msgstr "Disque externe ou partage réseau"

#: minarca_client/ui/backup_create.py:11
msgid "Offline accessibility"
msgstr "Accessibilité hors ligne"

#: minarca_client/ui/backup_create.py:11
msgid "Standalone backup"
msgstr "Sauvegarde autonome"

#: minarca_client/ui/backup_logs.py:26
msgid "Get detailed information about your last backup or restore operation."
msgstr ""
"Obtenez des informations détaillées sur votre dernière opération de sauvegarde "
"ou de restauration."

#: minarca_client/ui/backup_logs.py:26
msgid "Open file in text editor..."
msgstr "Ouvrir le fichier dans l'éditeur de texte..."

#: minarca_client/ui/backup_logs.py:26
msgid "Scroll to bottom"
msgstr "Défiler vers le bas"

#: minarca_client/ui/backup_logs.py:256
msgid "No log"
msgstr "Pas de journal"

#: minarca_client/ui/backup_logs.py:262
msgid "Restore logs"
msgstr "Journaux de restauration"

#: minarca_client/ui/backup_logs.py:263
msgid "Backup logs"
msgstr "Journaux de sauvegarde"

#: minarca_client/ui/backup_logs.py:270
#, python-format
msgid "Backup in progress for %s..."
msgstr "Sauvegarde en cours pour %s..."

#: minarca_client/ui/backup_logs.py:272
#, python-format
msgid "Data restoration in progress for %s..."
msgstr "Restauration des données en cours pour %s..."

#: minarca_client/ui/backup_logs.py:307
#, python-format
msgid "The last backup ended with the following error: %s"
msgstr "La dernière sauvegarde s'est terminée par l'erreur suivante : %s"

#: minarca_client/ui/backup_logs.py:309
#, python-format
msgid "The last restoration ended with the following error: %s"
msgstr "La dernière restauration s'est soldée par l'erreur suivante : %s"

#: minarca_client/ui/backup_logs.py:332
msgid "Confirmation Required"
msgstr "Confirmation requise"

#: minarca_client/ui/backup_logs.py:333
msgid "Are you sure you want to stop the ongoing backup/restore process?"
msgstr ""
"Êtes-vous sûr de vouloir arrêter le processus de sauvegarde/restauration en "
"cours ?"

#: minarca_client/ui/backup_logs.py:334
msgid ""
"Your data may be incomplete or corrupted if the operation is terminated "
"prematurely. Please confirm your decision before proceeding."
msgstr ""
"Vos données peuvent être incomplètes ou corrompues si l'opération est "
"interrompue prématurément. Veuillez confirmer votre décision avant de poursuivre."

#: minarca_client/ui/backup_patterns.py:23
msgid "Select the files and folders you want to back up."
msgstr "Sélectionnez les fichiers et les dossiers que vous souhaitez sauvegarder."

#: minarca_client/ui/backup_patterns.py:23
msgid "File Selection"
msgstr "Sélection des fichiers"

#: minarca_client/ui/backup_patterns.py:23
msgid "Files included"
msgstr "Fichiers inclus"

#: minarca_client/ui/backup_patterns.py:23
msgid "Files excluded"
msgstr "Fichiers exclus"

#: minarca_client/ui/backup_patterns.py:23 minarca_client/ui/backup_patterns.py:267
msgid "Add file"
msgstr "Ajouter un fichier"

#: minarca_client/ui/backup_patterns.py:23
msgid "Exclude file"
msgstr "Exclure un fichier"

#: minarca_client/ui/backup_patterns.py:23 minarca_client/ui/backup_patterns.py:256
msgid "Add folder"
msgstr "Ajouter un dossier"

#: minarca_client/ui/backup_patterns.py:23
msgid "Exclude folder"
msgstr "Exclure un dossier"

#: minarca_client/ui/backup_patterns.py:23
msgid "File extention (e.g.: *.txt)"
msgstr "Extention (ex. : *.txt)"

#: minarca_client/ui/backup_patterns.py:23
msgid "Exclude"
msgstr "Exclure"

#: minarca_client/ui/backup_patterns.py:23
msgid "Restore to default"
msgstr "Rétablir les valeurs par défaut"

#: minarca_client/ui/backup_restore_date.py:25
msgid "Choose the point in time of data to be restored."
msgstr "Choisissez le moment où les données doivent être restaurées."

#: minarca_client/ui/backup_restore_date.py:25
msgid "Select date & Time"
msgstr "Sélectionner la date et l'heure"

#: minarca_client/ui/backup_restore_date.py:172
msgid "Please wait. Loading backup dates..."
msgstr "Veuillez patienter. Chargement des dates de sauvegarde ..."

#: minarca_client/ui/backup_restore_date.py:180
msgid "Failed to retrieve available backup dates."
msgstr "Échec de la récupération des dates de sauvegarde disponibles."

#: minarca_client/ui/backup_restore_date.py:184
msgid "Unknown problem occurred when collecting backup dates."
msgstr ""
"Un problème inconnu s'est produit lors de la collecte des dates de sauvegarde."

#: minarca_client/ui/backup_restore_files.py:28
msgid ""
"When you perform a custom restore, the selected item is restored to a different "
"location selected by you."
msgstr ""
"Lorsque vous effectuez une restauration personnalisée, l'élément sélectionné est "
"restauré à un emplacement différent que vous avez choisi."

#: minarca_client/ui/backup_restore_files.py:28
msgid "Search for files or folders..."
msgstr "Recherche de fichiers ou dossiers..."

#: minarca_client/ui/backup_restore_files.py:28
msgid ""
"Restore files in-place, replacing existing files. I understand this may "
"overwrite data if the destination isn't empty."
msgstr ""
"Restaurer les fichiers sur place, en remplaçant les fichiers existants. Je "
"comprends que cela peut écraser des données si la destination n'est pas vide."

#: minarca_client/ui/backup_restore_files.py:28
msgid "Restore..."
msgstr "Restaurer..."

#: minarca_client/ui/backup_restore_files.py:211
msgid "Please wait. Getting file list..."
msgstr "Veuillez patienter. Obtention de la liste des fichiers..."

#: minarca_client/ui/backup_restore_files.py:231
msgid "Failed to retrieve available files."
msgstr "Échec de la récupération des fichiers disponibles."

#: minarca_client/ui/backup_restore_files.py:235
msgid "Unknown problem occurred when collecting file list."
msgstr ""
"Un problème inconnu s'est produit lors de la collecte de la liste des fichiers."

#: minarca_client/ui/backup_restore_files.py:259
#, python-format
msgid "%s item selected: %s"
msgid_plural "%s items selected: %s"
msgstr[0] "%s élément sélectionné : %s"
msgstr[1] "%s éléments sélectionnés : %s"

#: minarca_client/ui/backup_restore_files.py:260
msgid "No item selected"
msgstr "Aucun élément sélectionné"

#: minarca_client/ui/backup_restore_files.py:284
msgid "Confirm In-Place Restoration"
msgstr "Confirmer la restauration sur place"

#: minarca_client/ui/backup_restore_files.py:285
msgid "Are you sure you want to run a full restoration?"
msgstr "Êtes-vous sûr de vouloir effectuer une restauration complète ?"

#: minarca_client/ui/backup_restore_files.py:286
msgid ""
"This action will overwrite all existing files selected with the previous version "
"present in the backup. This action is irreversible and may result in data loss "
"if the destination is not empty."
msgstr ""
"Cette action écrasera tous les fichiers existants sélectionnés avec la version "
"précédente présente dans la sauvegarde. Cette action est irréversible et peut "
"entraîner une perte de données si la destination n'est pas vide."

#: minarca_client/ui/backup_restore_files.py:296
msgid "Select a folder where to restore data."
msgstr "Sélectionner le dossier dans lequel restaurer les données."

#: minarca_client/ui/backup_settings.py:26
msgid "Configure your backup settings for personalized data protection."
msgstr ""
"Configurez vos paramètres de sauvegarde pour une protection personnalisée des "
"données."

#: minarca_client/ui/backup_settings.py:26
msgid "Backup frequency"
msgstr "Fréquence de sauvegarde"

#: minarca_client/ui/backup_settings.py:26
msgid "Run whether the user's session is open or not"
msgstr "Exécuter si la session de l'utilisateur est ouverte ou non"

#: minarca_client/ui/backup_settings.py:26
msgid "Excluded Days of the Week"
msgstr "Jours de la semaine exclus"

#: minarca_client/ui/backup_settings.py:26
msgid "Monday"
msgstr "Lundi"

#: minarca_client/ui/backup_settings.py:26
msgid "Tuesday"
msgstr "Mardi"

#: minarca_client/ui/backup_settings.py:26
msgid "Wednesday"
msgstr "Mercredi"

#: minarca_client/ui/backup_settings.py:26
msgid "Thrusday"
msgstr "Jeudi"

#: minarca_client/ui/backup_settings.py:26
msgid "Friday"
msgstr "Vendredi"

#: minarca_client/ui/backup_settings.py:26
msgid "Saturday"
msgstr "Samedi"

#: minarca_client/ui/backup_settings.py:26
msgid "Sunday"
msgstr "Dimanche"

#: minarca_client/ui/backup_settings.py:26
msgid "Data Retention Duration"
msgstr "Durée de rétention des données"

#: minarca_client/ui/backup_settings.py:26
msgid "Inactivity Notification Period"
msgstr "Période d'avis d'inactivité"

#: minarca_client/ui/backup_settings.py:228
msgid "Please wait. Loading backup settings..."
msgstr "Veuillez patienter. Chargement des paramètres de sauvegarde..."

#: minarca_client/ui/backup_settings.py:251
msgid "Manual"
msgstr "Manuel"

#: minarca_client/ui/backup_settings.py:251
msgid "Hourly"
msgstr "Horaire"

#: minarca_client/ui/backup_settings.py:251
msgid "Four times a day"
msgstr "Quatre fois par jour"

#: minarca_client/ui/backup_settings.py:251
msgid "Twice a day"
msgstr "Deux fois par jour"

#: minarca_client/ui/backup_settings.py:251
msgid "Once a day"
msgstr "Une fois par jour"

#: minarca_client/ui/backup_settings.py:258
#: minarca_client/ui/backup_settings.py:277
msgid "1 day"
msgstr "1 jour"

#: minarca_client/ui/backup_settings.py:259
#: minarca_client/ui/backup_settings.py:278
msgid "2 days"
msgstr "2 jours"

#: minarca_client/ui/backup_settings.py:260
#: minarca_client/ui/backup_settings.py:279
msgid "3 days"
msgstr "3 jours"

#: minarca_client/ui/backup_settings.py:261
#: minarca_client/ui/backup_settings.py:280
msgid "4 days"
msgstr "4 jours"

#: minarca_client/ui/backup_settings.py:262
#: minarca_client/ui/backup_settings.py:281
msgid "5 days"
msgstr "5 jours"

#: minarca_client/ui/backup_settings.py:263
#: minarca_client/ui/backup_settings.py:282
msgid "6 days"
msgstr "6 jours"

#: minarca_client/ui/backup_settings.py:264
#: minarca_client/ui/backup_settings.py:283
msgid "1 week"
msgstr "1 semaine"

#: minarca_client/ui/backup_settings.py:265
#: minarca_client/ui/backup_settings.py:284
msgid "2 weeks"
msgstr "2 semaines"

#: minarca_client/ui/backup_settings.py:266
#: minarca_client/ui/backup_settings.py:285
msgid "3 weeks"
msgstr "3 semaines"

#: minarca_client/ui/backup_settings.py:267
msgid "4 weeks"
msgstr "4 semaines"

#: minarca_client/ui/backup_settings.py:268
#: minarca_client/ui/backup_settings.py:286
msgid "1 month"
msgstr "1 mois"

#: minarca_client/ui/backup_settings.py:276
msgid "Forever"
msgstr "Pour toujours"

#: minarca_client/ui/backup_settings.py:287
msgid "2 months"
msgstr "2 mois"

#: minarca_client/ui/backup_settings.py:288
msgid "3 months"
msgstr "3 mois"

#: minarca_client/ui/backup_settings.py:289
msgid "4 months"
msgstr "4 mois"

#: minarca_client/ui/backup_settings.py:290
msgid "5 months"
msgstr "5 mois"

#: minarca_client/ui/backup_settings.py:291
msgid "6 months"
msgstr "6 mois"

#: minarca_client/ui/backup_settings.py:292
msgid "7 months"
msgstr "7 mois"

#: minarca_client/ui/backup_settings.py:293
msgid "8 months"
msgstr "8 mois"

#: minarca_client/ui/backup_settings.py:294
msgid "9 months"
msgstr "9 mois"

#: minarca_client/ui/backup_settings.py:295
msgid "10 months"
msgstr "10 mois"

#: minarca_client/ui/backup_settings.py:296
msgid "11 months"
msgstr "11 mois"

#: minarca_client/ui/backup_settings.py:297
msgid "1 year"
msgstr "1 an"

#: minarca_client/ui/backup_settings.py:298
msgid "2 years"
msgstr "2 an"

#: minarca_client/ui/backup_settings.py:299
msgid "3 years"
msgstr "3 an"

#: minarca_client/ui/backup_settings.py:300
msgid "4 years"
msgstr "4 an"

#: minarca_client/ui/backup_settings.py:301
msgid "5 years"
msgstr "5 an"

#: minarca_client/ui/backup_settings.py:321
msgid "Unable to retrieve settings from remote server."
msgstr "Impossible de récupérer les paramètres du serveur distant."

#: minarca_client/ui/backup_settings.py:322
msgid ""
"This issue may arise due to the remote server being out-of-date. You may edit "
"the settings, however, some settings will not be synchronized with the remote "
"server. If this problem persists, we recommend contacting your administrator for "
"further assistance."
msgstr ""
"Ce problème peut être dû au fait que le serveur distant n'est pas à jour. Vous "
"pouvez modifier les paramètres, mais certains d'entre eux ne seront pas "
"synchronisés avec le serveur distant. Si ce problème persiste, nous vous "
"recommandons de contacter votre administrateur pour obtenir de l'aide."

#: minarca_client/ui/backup_settings.py:330
msgid "Unable to retrieve configuration from remote server."
msgstr "Impossible de récupérer la configuration du serveur distant."

#: minarca_client/ui/backup_settings.py:331
#, python-format
msgid ""
"An error occurred during the connection.\n"
"\n"
"Details: %s"
msgstr ""
"Une erreur s'est produite lors de la connexion.\n"
"\n"
"Détails : %s"

#: minarca_client/ui/backup_settings.py:380
msgid "Repository not found"
msgstr "Dépôt non trouvé"

#: minarca_client/ui/backup_settings.py:381
#: minarca_client/ui/backup_settings.py:403
msgid "A problem occured while trying to save the backup settings."
msgstr ""
"Un problème s'est produit lors de l'enregistrement des paramètres de sauvegarde."

#: minarca_client/ui/backup_settings.py:387
msgid "Authentication failed"
msgstr "Échec de l'authentification"

#: minarca_client/ui/backup_settings.py:388
msgid ""
"Your settings could not be saved to remote server. Do you want to continue ?"
msgstr ""
"Vos paramètres n'ont pas pu être enregistrés sur le serveur distant. Voulez-vous "
"continuer ?"

#: minarca_client/ui/backup_settings.py:389
msgid ""
"This issue may arise due to the remote server being out-of-date. You have the "
"option to proceed, however, some settings will not be synchronized with the "
"remote server. If this problem persists, we recommend contacting your "
"administrator for further assistance."
msgstr ""
"Ce problème peut être dû au fait que le serveur distant n'est pas à jour. Vous "
"avez la possibilité de continuer, mais certains paramètres ne seront pas "
"synchronisés avec le serveur distant. Si ce problème persiste, nous vous "
"recommandons de contacter votre administrateur pour obtenir de l'aide."

#: minarca_client/ui/backup_settings.py:402
msgid "Save Settings timeout"
msgstr "Délai d'enregistrement des paramètres est dépassé"

#: minarca_client/ui/backup_settings.py:404
msgid ""
"The operation timeout. Check your internet connection and verify if the remote "
"server is online. If the problem persist contact your administrator."
msgstr ""
"Le délai d'exécution de l'opération est dépassé. Vérifiez votre connexion "
"internet et vérifiez que le serveur distant est en ligne. Si le problème "
"persiste, contactez votre administrateur."

#: minarca_client/ui/backup_settings.py:412
msgid "Cannot save settings"
msgstr "Impossible d'enregistrer les paramètres"

#: minarca_client/ui/backup_settings.py:413
msgid ""
"An unknown problem occured while trying to save the backup settings. If the "
"problem persist contact your administrator."
msgstr ""
"Un problème inconnu s'est produit lors de l'enregistrement des paramètres de "
"sauvegarde. Si le problème persiste, contactez votre administrateur."

#: minarca_client/ui/backup_settings.py:462
msgid "Windows Credentials"
msgstr "Informations d'identification Windows"

#: minarca_client/ui/backup_settings.py:462
msgid "Enter credentials for local machine:"
msgstr "Saisir les informations d'identification de la machine locale :"

#: minarca_client/ui/backup_settings.py:467
msgid "Cannot apply your changes."
msgstr "Impossible d'appliquer les modifications."

#: minarca_client/ui/backup_settings.py:471
msgid "Backup Configuration"
msgstr "Configuration de la sauvegarde"

#: minarca_client/ui/dashboard.py:17
msgid "Dashboard"
msgstr "Tableau de bord"

#: minarca_client/ui/dashboard.py:17
msgid "Setup backup"
msgstr "Configurer une sauvegarde"

#: minarca_client/ui/side_pannel.py:98
msgid "Create an online backup"
msgstr "Créer une sauvegarde en ligne"

#: minarca_client/ui/side_pannel.py:100
msgid "Online restore"
msgstr "Restauration en ligne"

#: minarca_client/ui/side_pannel.py:105
msgid "Create a local backup"
msgstr "Créer une sauvegarde locale"

#: minarca_client/ui/side_pannel.py:107
msgid "Local restore"
msgstr "Restauration locale"

#~ msgid "Server connexion"
#~ msgstr "Connexion au serveur"

#~ msgid "Reset server connexion"
#~ msgstr "Connexion au serveur"

#~ msgid "Back on External Disk"
#~ msgstr "Médias externes /media"

#~ msgid "Add Folder Pattern"
#~ msgstr "Ajouter un modèle de dossier"

#~ msgid "Add File Pattern"
#~ msgstr "Ajouter un modèle de fichier"

#~ msgid "Select location where to backup your files."
#~ msgstr "Sélectionnez l'emplacement où vous souhaitez sauvegarder vos fichiers."

#~ msgid ""
#~ "A problem prevents the automatic scheduling of backup jobs. As a result, your "
#~ "backup tasks cannot be executed as planned."
#~ msgstr ""
#~ "Un problème empêche la planification automatique des tâches de sauvegarde. "
#~ "Par conséquent, vos tâches de sauvegarde ne peuvent pas être exécutées comme "
#~ "prévu."

#~ msgid "Process interrupted by user."
#~ msgstr "Processus interrompu par l'utilisateur."

#~ msgid ""
#~ "Choose between restoring all files in place or selecting specific files for "
#~ "restoration."
#~ msgstr ""
#~ "Vous pouvez choisir de restaurer tous les fichiers en place ou de "
#~ "sélectionner des fichiers spécifiques à restaurer."

#~ msgid "Restore Options"
#~ msgstr "Options de restauration"

#~ msgid "Custom restore"
#~ msgstr "Restauration personnalisée"

#~ msgid "Select file(s) to restore"
#~ msgstr "Sélectionner le(s) fichier(s) à restaurer"

#~ msgid "Select destination"
#~ msgstr "Sélectionner la destination"

#~ msgid "Ideal for quick recovery"
#~ msgstr "Idéal pour une récupération rapide"

#~ msgid "Full restore"
#~ msgstr "Restauration complète"

#~ msgid "Restore all files"
#~ msgstr "Restaurer tous les fichiers"

#~ msgid "Replace existing files"
#~ msgstr "Remplacer les fichiers existants"

#~ msgid "Ideal for hardware failure"
#~ msgstr "Idéal en cas de défaillance matérielle"

#~ msgid ""
#~ "When you perform a full restore, the selected items will be restored to their "
#~ "original location on your device."
#~ msgstr ""
#~ "Lorsque vous effectuez une restauration complète, les éléments sélectionnés "
#~ "sont restaurés à leur emplacement d'origine sur votre appareil."

#~ msgid ""
#~ "I understand that full restore replaces existing files on my device and may "
#~ "result in data loss if the destination is not empty."
#~ msgstr ""
#~ "Je comprends que la restauration complète remplace les fichiers existants sur "
#~ "mon appareil et peut entraîner une perte de données si la destination n'est "
#~ "pas vide."

#~ msgid "Restore"
#~ msgstr "Restaurer"

#~ msgid "No files included in backup. Check configuration. (Error: 29)"
#~ msgstr ""
#~ "Aucun fichier n'est inclus dans la sauvegarde. Vérifier la configuration."

#~ msgid "unexpected error during backup"
#~ msgstr "erreur inattendue pendant la sauvegarde"

#~ msgid "backup not running"
#~ msgstr "la sauvegarde ne s'exécute pas"
